package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_member_favorite
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsMemberFavorite implements Serializable{
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属bid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.BID
     *
     * @mbg.generated
     */
    private Integer bid;

    /**
     * Database Column Remarks:
     *   会员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.MEMBER_ID
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     * Database Column Remarks:
     *   房源ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.FAVORITE_ID
     *
     * @mbg.generated
     */
    private Integer favoriteId;

    /**
     * Database Column Remarks:
     *   类型；0: 房屋出租, 1:房屋出售,2:新楼盘
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.FAVORITE_TYPE
     *
     * @mbg.generated
     */
    private Integer favoriteType;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除：0：未删除，1：已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.PARAM1
     *
     * @mbg.generated
     */
    private String param1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.PARAM2
     *
     * @mbg.generated
     */
    private String param2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.PARAM3
     *
     * @mbg.generated
     */
    private String param3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.PARAM4
     *
     * @mbg.generated
     */
    private String param4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_favorite.PARAM5
     *
     * @mbg.generated
     */
    private String param5;

    /**
     * 是否收藏 0：已收藏 1：未收藏/取消收藏
     */
    private Integer isFavorite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.ID
     *
     * @return the value of hs_member_favorite.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.ID
     *
     * @param id the value for hs_member_favorite.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.BID
     *
     * @return the value of hs_member_favorite.BID
     *
     * @mbg.generated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.BID
     *
     * @param bid the value for hs_member_favorite.BID
     *
     * @mbg.generated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.MEMBER_ID
     *
     * @return the value of hs_member_favorite.MEMBER_ID
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.MEMBER_ID
     *
     * @param memberId the value for hs_member_favorite.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.FAVORITE_ID
     *
     * @return the value of hs_member_favorite.FAVORITE_ID
     *
     * @mbg.generated
     */
    public Integer getFavoriteId() {
        return favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.FAVORITE_ID
     *
     * @param favoriteId the value for hs_member_favorite.FAVORITE_ID
     *
     * @mbg.generated
     */
    public void setFavoriteId(Integer favoriteId) {
        this.favoriteId = favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.FAVORITE_TYPE
     *
     * @return the value of hs_member_favorite.FAVORITE_TYPE
     *
     * @mbg.generated
     */
    public Integer getFavoriteType() {
        return favoriteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.FAVORITE_TYPE
     *
     * @param favoriteType the value for hs_member_favorite.FAVORITE_TYPE
     *
     * @mbg.generated
     */
    public void setFavoriteType(Integer favoriteType) {
        this.favoriteType = favoriteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.REMARK
     *
     * @return the value of hs_member_favorite.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.REMARK
     *
     * @param remark the value for hs_member_favorite.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.CREATE_BY
     *
     * @return the value of hs_member_favorite.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.CREATE_BY
     *
     * @param createBy the value for hs_member_favorite.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.CREATE_TIME
     *
     * @return the value of hs_member_favorite.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.CREATE_TIME
     *
     * @param createTime the value for hs_member_favorite.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.UPDATE_BY
     *
     * @return the value of hs_member_favorite.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.UPDATE_BY
     *
     * @param updateBy the value for hs_member_favorite.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.UPDATE_TIME
     *
     * @return the value of hs_member_favorite.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.UPDATE_TIME
     *
     * @param updateTime the value for hs_member_favorite.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.is_del
     *
     * @return the value of hs_member_favorite.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.is_del
     *
     * @param isDel the value for hs_member_favorite.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.PARAM1
     *
     * @return the value of hs_member_favorite.PARAM1
     *
     * @mbg.generated
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.PARAM1
     *
     * @param param1 the value for hs_member_favorite.PARAM1
     *
     * @mbg.generated
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.PARAM2
     *
     * @return the value of hs_member_favorite.PARAM2
     *
     * @mbg.generated
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.PARAM2
     *
     * @param param2 the value for hs_member_favorite.PARAM2
     *
     * @mbg.generated
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.PARAM3
     *
     * @return the value of hs_member_favorite.PARAM3
     *
     * @mbg.generated
     */
    public String getParam3() {
        return param3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.PARAM3
     *
     * @param param3 the value for hs_member_favorite.PARAM3
     *
     * @mbg.generated
     */
    public void setParam3(String param3) {
        this.param3 = param3 == null ? null : param3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.PARAM4
     *
     * @return the value of hs_member_favorite.PARAM4
     *
     * @mbg.generated
     */
    public String getParam4() {
        return param4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.PARAM4
     *
     * @param param4 the value for hs_member_favorite.PARAM4
     *
     * @mbg.generated
     */
    public void setParam4(String param4) {
        this.param4 = param4 == null ? null : param4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_favorite.PARAM5
     *
     * @return the value of hs_member_favorite.PARAM5
     *
     * @mbg.generated
     */
    public String getParam5() {
        return param5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_favorite.PARAM5
     *
     * @param param5 the value for hs_member_favorite.PARAM5
     *
     * @mbg.generated
     */
    public void setParam5(String param5) {
        this.param5 = param5 == null ? null : param5.trim();
    }

    public Integer getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Integer isFavorite) {
        this.isFavorite = isFavorite;
    }
}