package www.ucforward.com.entity;

import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_member_housing_bargain_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsMemberHousingBargainMessage implements Serializable {
    /**
     * Database Column Remarks:
     *   议价id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   语言版本(0:中文,1:英文)默认为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    private Integer languageVersion;

    /**
     * Database Column Remarks:
     *   议价ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.BARGAIN_ID
     *
     * @mbg.generated
     */
    private Integer bargainId;

    /**
     * Database Column Remarks:
     *   起租日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.LEASE_START_DATE
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date leaseStartDate;

    /**
     * Database Column Remarks:
     *   租赁时长,单位年
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.LEASE_DURATION_YEAR
     *
     * @mbg.generated
     */
    @Min(value = 1,message = "租赁时长不能小于{value}")
    @Max(value = 12,message = "租赁时长不能大于{value}")
    //@NotNull
    private Integer leaseDurationYear;

    /**
     * Database Column Remarks:
     *   租金价格 单位 迪拉姆/年
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.LEASE_PRICE
     *
     * @mbg.generated
     */
    @NotNull
    private Integer leasePrice;

    /**
     * Database Column Remarks:
     *   支付节点 单位 1~12次/年
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.PAY_NODE
     *
     * @mbg.generated
     */
    private Integer payNode;

    /**
     * 过户日期
     */
    private Date transferDate;

    /**
     * 付款方式 0全款 1贷款
     */
    private Integer payType;

    /**
     * Database Column Remarks:
     *   业主是否已查看0:未查看，1：已查看
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.IS_OPEN
     *
     * @mbg.generated
     */
    private Integer isOpen;

    /**
     * Database Column Remarks:
     *   消息发送者 0 客户 1 业主
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.SENDER
     *
     * @mbg.generated
     */
    @NotNull
    private Integer sender;

    /**
     * Database Column Remarks:
     *   是否自动应答消息 0 否 1 是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.IS_AUTOMATIC
     *
     * @mbg.generated
     */
    private Integer isAutomatic;

    /**
     * Database Column Remarks:
     *   操作状态 0 协商 1 拒绝 2 同意 3 同意并允许生成合同
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.OPERATE_STATUS
     *
     * @mbg.generated
     */
    private Integer operateStatus;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   删除人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.DELETE_BY
     *
     * @mbg.generated
     */
    private Integer deleteBy;

    /**
     * Database Column Remarks:
     *   删除时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_housing_bargain_message.Integer
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.ID
     *
     * @return the value of hs_member_housing_bargain_message.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.ID
     *
     * @param id the value for hs_member_housing_bargain_message.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.LANGUAGE_VERSION
     *
     * @return the value of hs_member_housing_bargain_message.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public Integer getLanguageVersion() {
        return languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.LANGUAGE_VERSION
     *
     * @param languageVersion the value for hs_member_housing_bargain_message.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public void setLanguageVersion(Integer languageVersion) {
        this.languageVersion = languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.BARGAIN_ID
     *
     * @return the value of hs_member_housing_bargain_message.BARGAIN_ID
     *
     * @mbg.generated
     */
    public Integer getBargainId() {
        return bargainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.BARGAIN_ID
     *
     * @param bargainId the value for hs_member_housing_bargain_message.BARGAIN_ID
     *
     * @mbg.generated
     */
    public void setBargainId(Integer bargainId) {
        this.bargainId = bargainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.LEASE_START_DATE
     *
     * @return the value of hs_member_housing_bargain_message.LEASE_START_DATE
     *
     * @mbg.generated
     */
    public Date getLeaseStartDate() {
        return leaseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.LEASE_START_DATE
     *
     * @param leaseStartDate the value for hs_member_housing_bargain_message.LEASE_START_DATE
     *
     * @mbg.generated
     */
    public void setLeaseStartDate(Date leaseStartDate) {
        this.leaseStartDate = leaseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.LEASE_DURATION_YEAR
     *
     * @return the value of hs_member_housing_bargain_message.LEASE_DURATION_YEAR
     *
     * @mbg.generated
     */
    public Integer getLeaseDurationYear() {
        return leaseDurationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.LEASE_DURATION_YEAR
     *
     * @param leaseDurationYear the value for hs_member_housing_bargain_message.LEASE_DURATION_YEAR
     *
     * @mbg.generated
     */
    public void setLeaseDurationYear(Integer leaseDurationYear) {
        this.leaseDurationYear = leaseDurationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.LEASE_PRICE
     *
     * @return the value of hs_member_housing_bargain_message.LEASE_PRICE
     *
     * @mbg.generated
     */
    public Integer getLeasePrice() {
        return leasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.LEASE_PRICE
     *
     * @param leasePrice the value for hs_member_housing_bargain_message.LEASE_PRICE
     *
     * @mbg.generated
     */
    public void setLeasePrice(Integer leasePrice) {
        this.leasePrice = leasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.PAY_NODE
     *
     * @return the value of hs_member_housing_bargain_message.PAY_NODE
     *
     * @mbg.generated
     */
    public Integer getPayNode() {
        return payNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.PAY_NODE
     *
     * @param payNode the value for hs_member_housing_bargain_message.PAY_NODE
     *
     * @mbg.generated
     */
    public void setPayNode(Integer payNode) {
        this.payNode = payNode;
    }

    public Date getTransferDate() {
        return transferDate;
    }

    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    public Integer getPayType() {
        return payType;
    }

    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.IS_OPEN
     *
     * @return the value of hs_member_housing_bargain_message.IS_OPEN
     *
     * @mbg.generated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.IS_OPEN
     *
     * @param isOpen the value for hs_member_housing_bargain_message.IS_OPEN
     *
     * @mbg.generated
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.SENDER
     *
     * @return the value of hs_member_housing_bargain_message.SENDER
     *
     * @mbg.generated
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.SENDER
     *
     * @param sender the value for hs_member_housing_bargain_message.SENDER
     *
     * @mbg.generated
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.IS_AUTOMATIC
     *
     * @return the value of hs_member_housing_bargain_message.IS_AUTOMATIC
     *
     * @mbg.generated
     */
    public Integer getIsAutomatic() {
        return isAutomatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.IS_AUTOMATIC
     *
     * @param isAutomatic the value for hs_member_housing_bargain_message.IS_AUTOMATIC
     *
     * @mbg.generated
     */
    public void setIsAutomatic(Integer isAutomatic) {
        this.isAutomatic = isAutomatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.OPERATE_STATUS
     *
     * @return the value of hs_member_housing_bargain_message.OPERATE_STATUS
     *
     * @mbg.generated
     */
    public Integer getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.OPERATE_STATUS
     *
     * @param operateStatus the value for hs_member_housing_bargain_message.OPERATE_STATUS
     *
     * @mbg.generated
     */
    public void setOperateStatus(Integer operateStatus) {
        this.operateStatus = operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.REMARK
     *
     * @return the value of hs_member_housing_bargain_message.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.REMARK
     *
     * @param remark the value for hs_member_housing_bargain_message.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.CREATE_BY
     *
     * @return the value of hs_member_housing_bargain_message.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.CREATE_BY
     *
     * @param createBy the value for hs_member_housing_bargain_message.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.CREATE_TIME
     *
     * @return the value of hs_member_housing_bargain_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.CREATE_TIME
     *
     * @param createTime the value for hs_member_housing_bargain_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.UPDATE_BY
     *
     * @return the value of hs_member_housing_bargain_message.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.UPDATE_BY
     *
     * @param updateBy the value for hs_member_housing_bargain_message.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.UPDATE_TIME
     *
     * @return the value of hs_member_housing_bargain_message.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.UPDATE_TIME
     *
     * @param updateTime the value for hs_member_housing_bargain_message.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.DELETE_BY
     *
     * @return the value of hs_member_housing_bargain_message.DELETE_BY
     *
     * @mbg.generated
     */
    public Integer getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.DELETE_BY
     *
     * @param deleteBy the value for hs_member_housing_bargain_message.DELETE_BY
     *
     * @mbg.generated
     */
    public void setDeleteBy(Integer deleteBy) {
        this.deleteBy = deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_housing_bargain_message.DELETE_TIME
     *
     * @return the value of hs_member_housing_bargain_message.Integer
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_housing_bargain_message.DELETE_TIME
     *
     * @param isDel the value for hs_member_housing_bargain_message.Integer
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}