package www.ucforward.com.dao;

import www.ucforward.com.entity.HsHousingOrderRefund;

import java.util.Map;

public interface HsHousingOrderRefundDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    int insert(HsHousingOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    int insertSelective(HsHousingOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    HsHousingOrderRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsHousingOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsHousingOrderRefund record);

    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);
}