package com.example.demo.dao;

import com.example.demo.pojo.HsAdvertData;
import org.springframework.stereotype.Repository;

import java.util.Map;


@Repository
public interface HsAdvertDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    int insert(HsAdvertData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    int insertSelective(HsAdvertData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    HsAdvertData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsAdvertData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_advert_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsAdvertData record);

    /**
     * 自定义查询列
     * @param condition
     * @return
     */
    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);

}