package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_msg_sys
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsMsgSys implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名（手机号）特定推送给某个用户，或几个用户时使用。多个用户用逗号分割，最多50个
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户平台 外部:1 外获:2 外看:3  其他为测试
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.PLATFORM
     *
     * @mbg.generated
     */
    private Integer platform;

    /**
     * Database Column Remarks:
     *   推送客户端 0:所有用户 1:android 2:ios 3:个别用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.CLIENT
     *
     * @mbg.generated
     */
    private Integer client;

    /**
     * Database Column Remarks:
     *   消息类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.MSG_CODE
     *
     * @mbg.generated
     */
    private Integer msgCode;

    /**
     * Database Column Remarks:
     *   消息推送内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.ALERT
     *
     * @mbg.generated
     */
    private String alert;

    /**
     * Database Column Remarks:
     *   0未读 1已读
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.IS_READ
     *
     * @mbg.generated
     */
    private Integer isRead;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   是否删除,0：未删除，1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   消息详情 json对象
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_msg_sys.DETAILS
     *
     * @mbg.generated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.ID
     *
     * @return the value of hs_msg_sys.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.ID
     *
     * @param id the value for hs_msg_sys.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.USER_NAME
     *
     * @return the value of hs_msg_sys.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.USER_NAME
     *
     * @param userName the value for hs_msg_sys.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.PLATFORM
     *
     * @return the value of hs_msg_sys.PLATFORM
     *
     * @mbg.generated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.PLATFORM
     *
     * @param platform the value for hs_msg_sys.PLATFORM
     *
     * @mbg.generated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.CLIENT
     *
     * @return the value of hs_msg_sys.CLIENT
     *
     * @mbg.generated
     */
    public Integer getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.CLIENT
     *
     * @param client the value for hs_msg_sys.CLIENT
     *
     * @mbg.generated
     */
    public void setClient(Integer client) {
        this.client = client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.MSG_CODE
     *
     * @return the value of hs_msg_sys.MSG_CODE
     *
     * @mbg.generated
     */
    public Integer getMsgCode() {
        return msgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.MSG_CODE
     *
     * @param msgCode the value for hs_msg_sys.MSG_CODE
     *
     * @mbg.generated
     */
    public void setMsgCode(Integer msgCode) {
        this.msgCode = msgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.ALERT
     *
     * @return the value of hs_msg_sys.ALERT
     *
     * @mbg.generated
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.ALERT
     *
     * @param alert the value for hs_msg_sys.ALERT
     *
     * @mbg.generated
     */
    public void setAlert(String alert) {
        this.alert = alert == null ? null : alert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.IS_READ
     *
     * @return the value of hs_msg_sys.IS_READ
     *
     * @mbg.generated
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.IS_READ
     *
     * @param isRead the value for hs_msg_sys.IS_READ
     *
     * @mbg.generated
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.CREATE_TIME
     *
     * @return the value of hs_msg_sys.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.CREATE_TIME
     *
     * @param createTime the value for hs_msg_sys.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.CREATE_BY
     *
     * @return the value of hs_msg_sys.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.CREATE_BY
     *
     * @param createBy the value for hs_msg_sys.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.UPDATE_TIME
     *
     * @return the value of hs_msg_sys.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.UPDATE_TIME
     *
     * @param updateTime the value for hs_msg_sys.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.UPDATE_BY
     *
     * @return the value of hs_msg_sys.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.UPDATE_BY
     *
     * @param updateBy the value for hs_msg_sys.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.IS_DEL
     *
     * @return the value of hs_msg_sys.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.IS_DEL
     *
     * @param isDel the value for hs_msg_sys.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_msg_sys.DETAILS
     *
     * @return the value of hs_msg_sys.DETAILS
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_msg_sys.DETAILS
     *
     * @param details the value for hs_msg_sys.DETAILS
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}