package www.ucforward.com.dao;

import www.ucforward.com.entity.HsHousingOrderRefundApply;

import java.util.Map;

public interface HsHousingOrderRefundApplyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    int insert(HsHousingOrderRefundApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    int insertSelective(HsHousingOrderRefundApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    HsHousingOrderRefundApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsHousingOrderRefundApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_refund_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsHousingOrderRefundApply record);

    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);
}