package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_house_progress
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsHouseProgress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   房源ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.HOUSE_ID
     *
     * @mbg.generated
     */
    private Integer houseId;

    /**
     * 房源申请ID
     */
    private Integer applyId;

    /**
     * Database Column Remarks:
     *   房源进度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.PROGRESS_CODE
     *
     * @mbg.generated
     */
    private String progressCode;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_progress.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_progress.ID
     *
     * @return the value of hs_house_progress.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_progress.ID
     *
     * @param id the value for hs_house_progress.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_progress.HOUSE_ID
     *
     * @return the value of hs_house_progress.HOUSE_ID
     *
     * @mbg.generated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_progress.HOUSE_ID
     *
     * @param houseId the value for hs_house_progress.HOUSE_ID
     *
     * @mbg.generated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    public Integer getApplyId() {
        return applyId;
    }

    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    public String getProgressCode() {
        return progressCode;
    }

    public void setProgressCode(String progressCode) {
        this.progressCode = progressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_progress.CREATE_BY
     *
     * @return the value of hs_house_progress.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_progress.CREATE_BY
     *
     * @param createBy the value for hs_house_progress.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_progress.CREATE_TIME
     *
     * @return the value of hs_house_progress.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_progress.CREATE_TIME
     *
     * @param createTime the value for hs_house_progress.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_progress.UPDATE_TIME
     *
     * @return the value of hs_house_progress.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_progress.UPDATE_TIME
     *
     * @param updateTime the value for hs_house_progress.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}