package www.ucforward.com.dao;


import org.springframework.stereotype.Repository;
import www.ucforward.com.entity.HsMemberHousingApplicationMessage;

import java.util.List;
import java.util.Map;

@Repository
public interface HsMemberHousingApplicationMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    int insert(HsMemberHousingApplicationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    int insertSelective(HsMemberHousingApplicationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    HsMemberHousingApplicationMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsMemberHousingApplicationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_housing_application_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsMemberHousingApplicationMessage record);

    /**
     * 查询列表数据
     * @param condition 查询条件
     * @param returnType 返回值类型 0 List<Map> 1 List<Entity>
     * @return
     */
    Map<Object,Object> selectListByCondition(Map<Object,Object> condition, int returnType);

    /**
     * 自定义查询列
     * @param condition
     * @return
     */
    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);


    /**
     * 获取最后一条聊天信息
     * @param condition
     * @return
     */
    List<Map<String, Object>> getLastMsg(Map<Object,Object> condition);

    /**
     * 根据条件修改数据
     * @param condition
     * @return
     */
    Integer updateCustomColumnByCondition(Map<Object,Object> condition);
}