package www.ucforward.com.dao;


import org.springframework.stereotype.Repository;
import www.ucforward.com.entity.HsHouseComplainLog;

@Repository
public interface HsHouseComplainLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    int insert(HsHouseComplainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    int insertSelective(HsHouseComplainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    HsHouseComplainLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsHouseComplainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_complain_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsHouseComplainLog record);
}