package www.ucforward.com.dao;


import org.springframework.stereotype.Repository;
import www.ucforward.com.entity.HsHouseObtained;

import java.util.Map;

@Repository
public interface HsHouseObtainedDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    int insert(HsHouseObtained record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    int insertSelective(HsHouseObtained record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    HsHouseObtained selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsHouseObtained record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_house_obtained
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsHouseObtained record);

    /**
     * 自定义查询列
     * @param condition
     * @return
     */
    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);
}