package www.ucforward.com.dao;

import org.springframework.stereotype.Repository;
import www.ucforward.com.entity.HsMemberHousesSubscribe;

import java.util.Map;

@Repository
public interface HsMemberHousesSubscribeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    int insert(HsMemberHousesSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    int insertSelective(HsMemberHousesSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    HsMemberHousesSubscribe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsMemberHousesSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_member_houses_subscribe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsMemberHousesSubscribe record);

    /**
     * 查询列表数据
     * @param condition 查询参数
     * @param returnType 返回值类型 0 List<Map> 1 List<Entity>
     * @return
     */
    Map<Object,Object> selectListByCondition(Map<Object,Object> condition,int returnType);

    /**
     * 自定义查询列
     * @param condition
     * @return
     */
    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);
}