package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_region_code
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsRegionCode implements Serializable {
    /**
     * Database Column Remarks:
     *   城市编码id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   行政单位中文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.REGION_NAME_CN
     *
     * @mbg.generated
     */
    private String regionNameCn;

    /**
     * Database Column Remarks:
     *   行政单位英文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.REGION_NAME_EN
     *
     * @mbg.generated
     */
    private String regionNameEn;

    /**
     * Database Column Remarks:
     *   代号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.CODE_NAME
     *
     * @mbg.generated
     */
    private String codeName;

    /**
     * Database Column Remarks:
     *   国家码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.REGION_CODE
     *
     * @mbg.generated
     */
    private String regionCode;

    /**
     * Database Column Remarks:
     *   是否删除0:不删除，1：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_region_code.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.ID
     *
     * @return the value of hs_region_code.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.ID
     *
     * @param id the value for hs_region_code.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.REGION_NAME_CN
     *
     * @return the value of hs_region_code.REGION_NAME_CN
     *
     * @mbg.generated
     */
    public String getRegionNameCn() {
        return regionNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.REGION_NAME_CN
     *
     * @param regionNameCn the value for hs_region_code.REGION_NAME_CN
     *
     * @mbg.generated
     */
    public void setRegionNameCn(String regionNameCn) {
        this.regionNameCn = regionNameCn == null ? null : regionNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.REGION_NAME_EN
     *
     * @return the value of hs_region_code.REGION_NAME_EN
     *
     * @mbg.generated
     */
    public String getRegionNameEn() {
        return regionNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.REGION_NAME_EN
     *
     * @param regionNameEn the value for hs_region_code.REGION_NAME_EN
     *
     * @mbg.generated
     */
    public void setRegionNameEn(String regionNameEn) {
        this.regionNameEn = regionNameEn == null ? null : regionNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.CODE_NAME
     *
     * @return the value of hs_region_code.CODE_NAME
     *
     * @mbg.generated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.CODE_NAME
     *
     * @param codeName the value for hs_region_code.CODE_NAME
     *
     * @mbg.generated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.REGION_CODE
     *
     * @return the value of hs_region_code.REGION_CODE
     *
     * @mbg.generated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.REGION_CODE
     *
     * @param regionCode the value for hs_region_code.REGION_CODE
     *
     * @mbg.generated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.IS_DEL
     *
     * @return the value of hs_region_code.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.IS_DEL
     *
     * @param isDel the value for hs_region_code.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.CREATE_BY
     *
     * @return the value of hs_region_code.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.CREATE_BY
     *
     * @param createBy the value for hs_region_code.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.CREATE_TIME
     *
     * @return the value of hs_region_code.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.CREATE_TIME
     *
     * @param createTime the value for hs_region_code.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.UPDATE_BY
     *
     * @return the value of hs_region_code.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.UPDATE_BY
     *
     * @param updateBy the value for hs_region_code.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_region_code.UPDATE_TIME
     *
     * @return the value of hs_region_code.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_region_code.UPDATE_TIME
     *
     * @param updateTime the value for hs_region_code.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}