package www.ucforward.com.dao;


import www.ucforward.com.entity.HsMsgSetting;

import java.util.Map;

public interface HsMsgSettingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    int insert(HsMsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    int insertSelective(HsMsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    HsMsgSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsMsgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_msg_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsMsgSetting record);

    /**
     * 查询列表数据
     * @param condition 查询参数
     * @param returnType 返回值类型，0 List<Map>  1 list<Entity>
     * @return Map<Object,Object> result  key data,pageInfo
     * @throws Exception
     */
    Map<Object,Object> selectListByCondition(Map<Object, Object> condition, int returnType);
}