package www.ucforward.com.dao;

import www.ucforward.com.entity.HsSysDictcodeItem;

import java.util.List;
import java.util.Map;

public interface HsSysDictcodeItemDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    int insert(HsSysDictcodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    int insertSelective(HsSysDictcodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    HsSysDictcodeItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsSysDictcodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_sys_dictcode_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsSysDictcodeItem record);

    //查询所有
    Map<Object, Object> selectListByCondition(Map<Object, Object> condition, int returnType);

    /**
     * 自定义查询列
     * @param condition
     * @return
     */
    Map<Object,Object> selectCustomColumnNamesList(Map<Object, Object> condition);
}