package www.ucforward.com.dao;

import www.ucforward.com.entity.HsHousingOrderPaymentRecord;

public interface HsHousingOrderPaymentRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    int insert(HsHousingOrderPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    int insertSelective(HsHousingOrderPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    HsHousingOrderPaymentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HsHousingOrderPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_housing_order_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HsHousingOrderPaymentRecord record);
}