package www.ucforward.com.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dict_house_progress
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DictHouseProgress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   进度code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   进度（中文）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.ZH_CN
     *
     * @mbg.generated
     */
    private String zhCn;

    /**
     * Database Column Remarks:
     *   进度（英文）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.EN_US
     *
     * @mbg.generated
     */
    private String enUs;

    /**
     * Database Column Remarks:
     *   角色类型，逗号（,）分隔 1 业主；10业主(出租)；11业主(出售)；2 租客 3 买家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   进度顺序，与角色类型（TYPE）相对应
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_house_progress.SORT
     *
     * @mbg.generated
     */
    private String sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.ID
     *
     * @return the value of dict_house_progress.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.ID
     *
     * @param id the value for dict_house_progress.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.CODE
     *
     * @return the value of dict_house_progress.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.CODE
     *
     * @param code the value for dict_house_progress.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.ZH_CN
     *
     * @return the value of dict_house_progress.ZH_CN
     *
     * @mbg.generated
     */
    public String getZhCn() {
        return zhCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.ZH_CN
     *
     * @param zhCn the value for dict_house_progress.ZH_CN
     *
     * @mbg.generated
     */
    public void setZhCn(String zhCn) {
        this.zhCn = zhCn == null ? null : zhCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.EN_US
     *
     * @return the value of dict_house_progress.EN_US
     *
     * @mbg.generated
     */
    public String getEnUs() {
        return enUs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.EN_US
     *
     * @param enUs the value for dict_house_progress.EN_US
     *
     * @mbg.generated
     */
    public void setEnUs(String enUs) {
        this.enUs = enUs == null ? null : enUs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.TYPE
     *
     * @return the value of dict_house_progress.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.TYPE
     *
     * @param type the value for dict_house_progress.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_house_progress.SORT
     *
     * @return the value of dict_house_progress.SORT
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_house_progress.SORT
     *
     * @param sort the value for dict_house_progress.SORT
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }
}