package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_booth_house_rel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsBoothHouseRel implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   语言版本（0：中文，1：英文）默认为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    private Integer languageVersion;

    /**
     * Database Column Remarks:
     *   二手房源ID,
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.HOUSE_ID
     *
     * @mbg.generated
     */
    private Integer houseId;

    /**
     * Database Column Remarks:
     *   新房源ID,
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.NEW_HOUSE_ID
     *
     * @mbg.generated
     */
    private Integer newHouseId;

    /**
     * Database Column Remarks:
     *   展位ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.BOOTH_ID
     *
     * @mbg.generated
     */
    private Integer boothId;

    /**
     * Database Column Remarks:
     *   排序序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.AD_SN
     *
     * @mbg.generated
     */
    private Integer adSn;

    /**
     * Database Column Remarks:
     *   是否删除0:不删除，1：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   所对应的business主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.BID
     *
     * @mbg.generated
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_booth_house_rel.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.ID
     *
     * @return the value of hs_booth_house_rel.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.ID
     *
     * @param id the value for hs_booth_house_rel.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.LANGUAGE_VERSION
     *
     * @return the value of hs_booth_house_rel.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public Integer getLanguageVersion() {
        return languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.LANGUAGE_VERSION
     *
     * @param languageVersion the value for hs_booth_house_rel.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public void setLanguageVersion(Integer languageVersion) {
        this.languageVersion = languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.HOUSE_ID
     *
     * @return the value of hs_booth_house_rel.HOUSE_ID
     *
     * @mbg.generated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.HOUSE_ID
     *
     * @param houseId the value for hs_booth_house_rel.HOUSE_ID
     *
     * @mbg.generated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.NEW_HOUSE_ID
     *
     * @return the value of hs_booth_house_rel.NEW_HOUSE_ID
     *
     * @mbg.generated
     */
    public Integer getNewHouseId() {
        return newHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.NEW_HOUSE_ID
     *
     * @param newHouseId the value for hs_booth_house_rel.NEW_HOUSE_ID
     *
     * @mbg.generated
     */
    public void setNewHouseId(Integer newHouseId) {
        this.newHouseId = newHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.BOOTH_ID
     *
     * @return the value of hs_booth_house_rel.BOOTH_ID
     *
     * @mbg.generated
     */
    public Integer getBoothId() {
        return boothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.BOOTH_ID
     *
     * @param boothId the value for hs_booth_house_rel.BOOTH_ID
     *
     * @mbg.generated
     */
    public void setBoothId(Integer boothId) {
        this.boothId = boothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.AD_SN
     *
     * @return the value of hs_booth_house_rel.AD_SN
     *
     * @mbg.generated
     */
    public Integer getAdSn() {
        return adSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.AD_SN
     *
     * @param adSn the value for hs_booth_house_rel.AD_SN
     *
     * @mbg.generated
     */
    public void setAdSn(Integer adSn) {
        this.adSn = adSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.IS_DEL
     *
     * @return the value of hs_booth_house_rel.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.IS_DEL
     *
     * @param isDel the value for hs_booth_house_rel.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.CREATE_BY
     *
     * @return the value of hs_booth_house_rel.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.CREATE_BY
     *
     * @param createBy the value for hs_booth_house_rel.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.CREATE_TIME
     *
     * @return the value of hs_booth_house_rel.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.CREATE_TIME
     *
     * @param createTime the value for hs_booth_house_rel.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.UPDATE_BY
     *
     * @return the value of hs_booth_house_rel.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.UPDATE_BY
     *
     * @param updateBy the value for hs_booth_house_rel.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.UPDATE_TIME
     *
     * @return the value of hs_booth_house_rel.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.UPDATE_TIME
     *
     * @param updateTime the value for hs_booth_house_rel.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.BID
     *
     * @return the value of hs_booth_house_rel.BID
     *
     * @mbg.generated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.BID
     *
     * @param bid the value for hs_booth_house_rel.BID
     *
     * @mbg.generated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.STANDBY1
     *
     * @return the value of hs_booth_house_rel.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.STANDBY1
     *
     * @param standby1 the value for hs_booth_house_rel.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.STANDBY2
     *
     * @return the value of hs_booth_house_rel.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.STANDBY2
     *
     * @param standby2 the value for hs_booth_house_rel.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.STANDBY3
     *
     * @return the value of hs_booth_house_rel.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.STANDBY3
     *
     * @param standby3 the value for hs_booth_house_rel.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.STANDBY4
     *
     * @return the value of hs_booth_house_rel.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.STANDBY4
     *
     * @param standby4 the value for hs_booth_house_rel.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_booth_house_rel.STANDBY5
     *
     * @return the value of hs_booth_house_rel.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_booth_house_rel.STANDBY5
     *
     * @param standby5 the value for hs_booth_house_rel.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}