package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_gold_rule
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsGoldRule implements Serializable{
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   积分编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.GOLD_CODE
     *
     * @mbg.generated
     */
    private String goldCode;

    /**
     * Database Column Remarks:
     *   0：推荐并注册会员 1：外获上传任务完成，2：区域长上传任务完成，3：外看任务完成，4：区域长送钥匙完成，5：合同单任务完成 6 第一个业务员获取钥匙
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.GOLD_TYPE
     *
     * @mbg.generated
     */
    private Integer goldType;

    /**
     * Database Column Remarks:
     *   积分名称中文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.GOLD_RULE_NAME_CN
     *
     * @mbg.generated
     */
    private String goldRuleNameCn;

    /**
     * Database Column Remarks:
     *   积分名称英文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.GOLD_RULE_NAME_EN
     *
     * @mbg.generated
     */
    private String goldRuleNameEn;

    /**
     * Database Column Remarks:
     *   控制加分还是减分 0 ：加分 1减分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.IS_ADD_SUBTRACT
     *
     * @mbg.generated
     */
    private Integer isAddSubtract;

    /**
     * Database Column Remarks:
     *   是否是业务员 0 ：业务员 1 会员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.IS_SALESMAN
     *
     * @mbg.generated
     */
    private Integer isSalesman;

    /**
     * Database Column Remarks:
     *  是否删除,0：未删除，1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.IS_SALESMAN
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   积分值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.SCORE
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * Database Column Remarks:
     *   备注描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_gold_rule.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.ID
     *
     * @return the value of hs_gold_rule.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.ID
     *
     * @param id the value for hs_gold_rule.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.GOLD_CODE
     *
     * @return the value of hs_gold_rule.GOLD_CODE
     *
     * @mbg.generated
     */
    public String getGoldCode() {
        return goldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.GOLD_CODE
     *
     * @param goldCode the value for hs_gold_rule.GOLD_CODE
     *
     * @mbg.generated
     */
    public void setGoldCode(String goldCode) {
        this.goldCode = goldCode == null ? null : goldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.GOLD_TYPE
     *
     * @return the value of hs_gold_rule.GOLD_TYPE
     *
     * @mbg.generated
     */
    public Integer getGoldType() {
        return goldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.GOLD_TYPE
     *
     * @param goldType the value for hs_gold_rule.GOLD_TYPE
     *
     * @mbg.generated
     */
    public void setGoldType(Integer goldType) {
        this.goldType = goldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.GOLD_RULE_NAME_CN
     *
     * @return the value of hs_gold_rule.GOLD_RULE_NAME_CN
     *
     * @mbg.generated
     */
    public String getGoldRuleNameCn() {
        return goldRuleNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.GOLD_RULE_NAME_CN
     *
     * @param goldRuleNameCn the value for hs_gold_rule.GOLD_RULE_NAME_CN
     *
     * @mbg.generated
     */
    public void setGoldRuleNameCn(String goldRuleNameCn) {
        this.goldRuleNameCn = goldRuleNameCn == null ? null : goldRuleNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.GOLD_RULE_NAME_EN
     *
     * @return the value of hs_gold_rule.GOLD_RULE_NAME_EN
     *
     * @mbg.generated
     */
    public String getGoldRuleNameEn() {
        return goldRuleNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.GOLD_RULE_NAME_EN
     *
     * @param goldRuleNameEn the value for hs_gold_rule.GOLD_RULE_NAME_EN
     *
     * @mbg.generated
     */
    public void setGoldRuleNameEn(String goldRuleNameEn) {
        this.goldRuleNameEn = goldRuleNameEn == null ? null : goldRuleNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.IS_ADD_SUBTRACT
     *
     * @return the value of hs_gold_rule.IS_ADD_SUBTRACT
     *
     * @mbg.generated
     */
    public Integer getIsAddSubtract() {
        return isAddSubtract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.IS_ADD_SUBTRACT
     *
     * @param isAddSubtract the value for hs_gold_rule.IS_ADD_SUBTRACT
     *
     * @mbg.generated
     */
    public void setIsAddSubtract(Integer isAddSubtract) {
        this.isAddSubtract = isAddSubtract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.IS_SALESMAN
     *
     * @return the value of hs_gold_rule.IS_SALESMAN
     *
     * @mbg.generated
     */
    public Integer getIsSalesman() {
        return isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.IS_SALESMAN
     *
     * @param isSalesman the value for hs_gold_rule.IS_SALESMAN
     *
     * @mbg.generated
     */
    public void setIsSalesman(Integer isSalesman) {
        this.isSalesman = isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.SCORE
     *
     * @return the value of hs_gold_rule.SCORE
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.SCORE
     *
     * @param score the value for hs_gold_rule.SCORE
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.REMARK
     *
     * @return the value of hs_gold_rule.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.REMARK
     *
     * @param remark the value for hs_gold_rule.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.CREATE_BY
     *
     * @return the value of hs_gold_rule.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.CREATE_BY
     *
     * @param createBy the value for hs_gold_rule.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.CREATE_TIME
     *
     * @return the value of hs_gold_rule.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.CREATE_TIME
     *
     * @param createTime the value for hs_gold_rule.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.UPDATE_BY
     *
     * @return the value of hs_gold_rule.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.UPDATE_BY
     *
     * @param updateBy the value for hs_gold_rule.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.UPDATE_TIME
     *
     * @return the value of hs_gold_rule.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.UPDATE_TIME
     *
     * @param updateTime the value for hs_gold_rule.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.STANDBY1
     *
     * @return the value of hs_gold_rule.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.STANDBY1
     *
     * @param standby1 the value for hs_gold_rule.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.STANDBY2
     *
     * @return the value of hs_gold_rule.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.STANDBY2
     *
     * @param standby2 the value for hs_gold_rule.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.STANDBY3
     *
     * @return the value of hs_gold_rule.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.STANDBY3
     *
     * @param standby3 the value for hs_gold_rule.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.STANDBY4
     *
     * @return the value of hs_gold_rule.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.STANDBY4
     *
     * @param standby4 the value for hs_gold_rule.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_gold_rule.STANDBY5
     *
     * @return the value of hs_gold_rule.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_gold_rule.STANDBY5
     *
     * @param standby5 the value for hs_gold_rule.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }

    public Integer getIsDel() {
        return isDel;
    }

    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}