package www.ucforward.com.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_housing_order_payment_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsHousingOrderPaymentRecord implements Serializable{
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   来源订单主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.ORDER_ID
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   订单线上支付流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.ORDER_SERIAL_CODE
     *
     * @mbg.generated
     */
    private String orderSerialCode;

    /**
     * Database Column Remarks:
     *   支付方式 1-线上支付 2-线下支付 3-钱包支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.PAY_WAY
     *
     * @mbg.generated
     */
    private Integer payWay;

    /**
     * Database Column Remarks:
     *   付款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.PROCEEDS_AMOUT
     *
     * @mbg.generated
     */
    private BigDecimal proceedsAmout;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.POST_TIME
     *
     * @mbg.generated
     */
    private Date postTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   是否删除0:不删除，1：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_payment_record.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.ID
     *
     * @return the value of hs_housing_order_payment_record.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.ID
     *
     * @param id the value for hs_housing_order_payment_record.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.ORDER_ID
     *
     * @return the value of hs_housing_order_payment_record.ORDER_ID
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.ORDER_ID
     *
     * @param orderId the value for hs_housing_order_payment_record.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.ORDER_SERIAL_CODE
     *
     * @return the value of hs_housing_order_payment_record.ORDER_SERIAL_CODE
     *
     * @mbg.generated
     */
    public String getOrderSerialCode() {
        return orderSerialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.ORDER_SERIAL_CODE
     *
     * @param orderSerialCode the value for hs_housing_order_payment_record.ORDER_SERIAL_CODE
     *
     * @mbg.generated
     */
    public void setOrderSerialCode(String orderSerialCode) {
        this.orderSerialCode = orderSerialCode == null ? null : orderSerialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.PAY_WAY
     *
     * @return the value of hs_housing_order_payment_record.PAY_WAY
     *
     * @mbg.generated
     */
    public Integer getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.PAY_WAY
     *
     * @param payWay the value for hs_housing_order_payment_record.PAY_WAY
     *
     * @mbg.generated
     */
    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.PROCEEDS_AMOUT
     *
     * @return the value of hs_housing_order_payment_record.PROCEEDS_AMOUT
     *
     * @mbg.generated
     */
    public BigDecimal getProceedsAmout() {
        return proceedsAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.PROCEEDS_AMOUT
     *
     * @param proceedsAmout the value for hs_housing_order_payment_record.PROCEEDS_AMOUT
     *
     * @mbg.generated
     */
    public void setProceedsAmout(BigDecimal proceedsAmout) {
        this.proceedsAmout = proceedsAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.CREATE_BY
     *
     * @return the value of hs_housing_order_payment_record.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.CREATE_BY
     *
     * @param createBy the value for hs_housing_order_payment_record.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.CREATE_TIME
     *
     * @return the value of hs_housing_order_payment_record.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.CREATE_TIME
     *
     * @param createTime the value for hs_housing_order_payment_record.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.UPDATE_BY
     *
     * @return the value of hs_housing_order_payment_record.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.UPDATE_BY
     *
     * @param updateBy the value for hs_housing_order_payment_record.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.UPDATE_TIME
     *
     * @return the value of hs_housing_order_payment_record.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.UPDATE_TIME
     *
     * @param updateTime the value for hs_housing_order_payment_record.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.POST_TIME
     *
     * @return the value of hs_housing_order_payment_record.POST_TIME
     *
     * @mbg.generated
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.POST_TIME
     *
     * @param postTime the value for hs_housing_order_payment_record.POST_TIME
     *
     * @mbg.generated
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.REMARKS
     *
     * @return the value of hs_housing_order_payment_record.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.REMARKS
     *
     * @param remarks the value for hs_housing_order_payment_record.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.IS_DEL
     *
     * @return the value of hs_housing_order_payment_record.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.IS_DEL
     *
     * @param isDel the value for hs_housing_order_payment_record.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.STANDBY1
     *
     * @return the value of hs_housing_order_payment_record.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.STANDBY1
     *
     * @param standby1 the value for hs_housing_order_payment_record.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.STANDBY2
     *
     * @return the value of hs_housing_order_payment_record.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.STANDBY2
     *
     * @param standby2 the value for hs_housing_order_payment_record.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.STANDBY3
     *
     * @return the value of hs_housing_order_payment_record.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.STANDBY3
     *
     * @param standby3 the value for hs_housing_order_payment_record.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.STANDBY4
     *
     * @return the value of hs_housing_order_payment_record.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.STANDBY4
     *
     * @param standby4 the value for hs_housing_order_payment_record.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_payment_record.STANDBY5
     *
     * @return the value of hs_housing_order_payment_record.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_payment_record.STANDBY5
     *
     * @param standby5 the value for hs_housing_order_payment_record.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}