package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_housing_order_refund_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsHousingOrderRefundLog implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   退款id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.REFUND_ID
     *
     * @mbg.generated
     */
    private Integer refundId;

    /**
     * Database Column Remarks:
     *   退款状态 0申请退款 1主管审核通过 2财务审核通过(退款完成) 3退款失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.REFUND_STATUS
     *
     * @mbg.generated
     */
    private Integer refundStatus;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_housing_order_refund_log.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.ID
     *
     * @return the value of hs_housing_order_refund_log.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.ID
     *
     * @param id the value for hs_housing_order_refund_log.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.REFUND_ID
     *
     * @return the value of hs_housing_order_refund_log.REFUND_ID
     *
     * @mbg.generated
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.REFUND_ID
     *
     * @param refundId the value for hs_housing_order_refund_log.REFUND_ID
     *
     * @mbg.generated
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.REFUND_STATUS
     *
     * @return the value of hs_housing_order_refund_log.REFUND_STATUS
     *
     * @mbg.generated
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.REFUND_STATUS
     *
     * @param refundStatus the value for hs_housing_order_refund_log.REFUND_STATUS
     *
     * @mbg.generated
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.REMARK
     *
     * @return the value of hs_housing_order_refund_log.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.REMARK
     *
     * @param remark the value for hs_housing_order_refund_log.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.CREATE_BY
     *
     * @return the value of hs_housing_order_refund_log.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.CREATE_BY
     *
     * @param createBy the value for hs_housing_order_refund_log.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.CREATE_TIME
     *
     * @return the value of hs_housing_order_refund_log.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.CREATE_TIME
     *
     * @param createTime the value for hs_housing_order_refund_log.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.UPDATE_BY
     *
     * @return the value of hs_housing_order_refund_log.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.UPDATE_BY
     *
     * @param updateBy the value for hs_housing_order_refund_log.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.UPDATE_TIME
     *
     * @return the value of hs_housing_order_refund_log.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.UPDATE_TIME
     *
     * @param updateTime the value for hs_housing_order_refund_log.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.STANDBY1
     *
     * @return the value of hs_housing_order_refund_log.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.STANDBY1
     *
     * @param standby1 the value for hs_housing_order_refund_log.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.STANDBY2
     *
     * @return the value of hs_housing_order_refund_log.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.STANDBY2
     *
     * @param standby2 the value for hs_housing_order_refund_log.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.STANDBY3
     *
     * @return the value of hs_housing_order_refund_log.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.STANDBY3
     *
     * @param standby3 the value for hs_housing_order_refund_log.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.STANDBY4
     *
     * @return the value of hs_housing_order_refund_log.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.STANDBY4
     *
     * @param standby4 the value for hs_housing_order_refund_log.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_housing_order_refund_log.STANDBY5
     *
     * @return the value of hs_housing_order_refund_log.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_housing_order_refund_log.STANDBY5
     *
     * @param standby5 the value for hs_housing_order_refund_log.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}