package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_house_key_cases
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsHouseKeyCases implements Serializable {
    /**
     * Database Column Remarks:
     *   编号ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   房源ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.HOUSE_ID
     *
     * @mbg.generated
     */
    private Integer houseId;

    /**
     * Database Column Remarks:
     *   房源编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.HOUSE_CODE
     *
     * @mbg.generated
     */
    private String houseCode;

    /**
     * Database Column Remarks:
     *   业主ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.MEMBER_ID
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     * Database Column Remarks:
     *   业务员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   是否过期 0:未过期，1：已过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.IS_EXPIRE
     *
     * @mbg.generated
     */
    private Integer isExpire;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_key_cases.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.ID
     *
     * @return the value of hs_house_key_cases.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.ID
     *
     * @param id the value for hs_house_key_cases.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.HOUSE_ID
     *
     * @return the value of hs_house_key_cases.HOUSE_ID
     *
     * @mbg.generated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.HOUSE_ID
     *
     * @param houseId the value for hs_house_key_cases.HOUSE_ID
     *
     * @mbg.generated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.HOUSE_CODE
     *
     * @return the value of hs_house_key_cases.HOUSE_CODE
     *
     * @mbg.generated
     */
    public String getHouseCode() {
        return houseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.HOUSE_CODE
     *
     * @param houseCode the value for hs_house_key_cases.HOUSE_CODE
     *
     * @mbg.generated
     */
    public void setHouseCode(String houseCode) {
        this.houseCode = houseCode == null ? null : houseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.MEMBER_ID
     *
     * @return the value of hs_house_key_cases.MEMBER_ID
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.MEMBER_ID
     *
     * @param memberId the value for hs_house_key_cases.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.USER_ID
     *
     * @return the value of hs_house_key_cases.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.USER_ID
     *
     * @param userId the value for hs_house_key_cases.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.IS_EXPIRE
     *
     * @return the value of hs_house_key_cases.IS_EXPIRE
     *
     * @mbg.generated
     */
    public Integer getIsExpire() {
        return isExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.IS_EXPIRE
     *
     * @param isExpire the value for hs_house_key_cases.IS_EXPIRE
     *
     * @mbg.generated
     */
    public void setIsExpire(Integer isExpire) {
        this.isExpire = isExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.CREATE_BY
     *
     * @return the value of hs_house_key_cases.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.CREATE_BY
     *
     * @param createBy the value for hs_house_key_cases.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.CREATE_TIME
     *
     * @return the value of hs_house_key_cases.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.CREATE_TIME
     *
     * @param createTime the value for hs_house_key_cases.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.UPDATE_BY
     *
     * @return the value of hs_house_key_cases.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.UPDATE_BY
     *
     * @param updateBy the value for hs_house_key_cases.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.UPDATE_TIME
     *
     * @return the value of hs_house_key_cases.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.UPDATE_TIME
     *
     * @param updateTime the value for hs_house_key_cases.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.REMARKS
     *
     * @return the value of hs_house_key_cases.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.REMARKS
     *
     * @param remarks the value for hs_house_key_cases.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.STANDBY1
     *
     * @return the value of hs_house_key_cases.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.STANDBY1
     *
     * @param standby1 the value for hs_house_key_cases.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.STANDBY2
     *
     * @return the value of hs_house_key_cases.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.STANDBY2
     *
     * @param standby2 the value for hs_house_key_cases.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_key_cases.STANDBY3
     *
     * @return the value of hs_house_key_cases.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_key_cases.STANDBY3
     *
     * @param standby3 the value for hs_house_key_cases.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }
}