package www.ucforward.com.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_member_financial_loans_apply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsMemberFinancialLoansApply implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   会员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.MEMBER_ID
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     * Database Column Remarks:
     *   姓氏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.FAMILY_NAME
     *
     * @mbg.generated
     */
    private String familyName;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别(0:女性,1:男性)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.SEX
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   出生年月日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.DATE_BIRTH
     *
     * @mbg.generated
     */
    private Date dateBirth;

    /**
     * Database Column Remarks:
     *   是否结婚(0:未婚,1:已婚)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.IS_MARRIED
     *
     * @mbg.generated
     */
    private Integer isMarried;

    /**
     * Database Column Remarks:
     *   是否有子女(0:没有,1:有)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.HAVE_CHILDREN
     *
     * @mbg.generated
     */
    private Integer haveChildren;

    /**
     * Database Column Remarks:
     *   国籍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.NATIONALITY
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     * Database Column Remarks:
     *   护照号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.PASSPORT_NUMBER
     *
     * @mbg.generated
     */
    private String passportNumber;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   贷款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal loanAmount;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   facebook
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.FACEBOOK
     *
     * @mbg.generated
     */
    private String facebook;

    /**
     * Database Column Remarks:
     *   twitter
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.TWITTER
     *
     * @mbg.generated
     */
    private String twitter;

    /**
     * Database Column Remarks:
     *   instagram
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.INSTAGRAM
     *
     * @mbg.generated
     */
    private String instagram;

    /**
     * Database Column Remarks:
     *   pinterest
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.PINTEREST
     *
     * @mbg.generated
     */
    private String pinterest;

    /**
     * Database Column Remarks:
     *   是否审核,0：未审核，1审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.IS_CHECK
     *
     * @mbg.generated
     */
    private Integer isCheck;

    /**
     * Database Column Remarks:
     *   是否处理,0：未处理，1已处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.IS_PROCESSOR
     *
     * @mbg.generated
     */
    private Integer isProcessor;

    /**
     * Database Column Remarks:
     *   是否删除,0：未删除，1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   备注描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_member_financial_loans_apply.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.ID
     *
     * @return the value of hs_member_financial_loans_apply.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.ID
     *
     * @param id the value for hs_member_financial_loans_apply.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.MEMBER_ID
     *
     * @return the value of hs_member_financial_loans_apply.MEMBER_ID
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.MEMBER_ID
     *
     * @param memberId the value for hs_member_financial_loans_apply.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.FAMILY_NAME
     *
     * @return the value of hs_member_financial_loans_apply.FAMILY_NAME
     *
     * @mbg.generated
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.FAMILY_NAME
     *
     * @param familyName the value for hs_member_financial_loans_apply.FAMILY_NAME
     *
     * @mbg.generated
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.NAME
     *
     * @return the value of hs_member_financial_loans_apply.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.NAME
     *
     * @param name the value for hs_member_financial_loans_apply.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.SEX
     *
     * @return the value of hs_member_financial_loans_apply.SEX
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.SEX
     *
     * @param sex the value for hs_member_financial_loans_apply.SEX
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.DATE_BIRTH
     *
     * @return the value of hs_member_financial_loans_apply.DATE_BIRTH
     *
     * @mbg.generated
     */
    public Date getDateBirth() {
        return dateBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.DATE_BIRTH
     *
     * @param dateBirth the value for hs_member_financial_loans_apply.DATE_BIRTH
     *
     * @mbg.generated
     */
    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.IS_MARRIED
     *
     * @return the value of hs_member_financial_loans_apply.IS_MARRIED
     *
     * @mbg.generated
     */
    public Integer getIsMarried() {
        return isMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.IS_MARRIED
     *
     * @param isMarried the value for hs_member_financial_loans_apply.IS_MARRIED
     *
     * @mbg.generated
     */
    public void setIsMarried(Integer isMarried) {
        this.isMarried = isMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.HAVE_CHILDREN
     *
     * @return the value of hs_member_financial_loans_apply.HAVE_CHILDREN
     *
     * @mbg.generated
     */
    public Integer getHaveChildren() {
        return haveChildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.HAVE_CHILDREN
     *
     * @param haveChildren the value for hs_member_financial_loans_apply.HAVE_CHILDREN
     *
     * @mbg.generated
     */
    public void setHaveChildren(Integer haveChildren) {
        this.haveChildren = haveChildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.NATIONALITY
     *
     * @return the value of hs_member_financial_loans_apply.NATIONALITY
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.NATIONALITY
     *
     * @param nationality the value for hs_member_financial_loans_apply.NATIONALITY
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.PASSPORT_NUMBER
     *
     * @return the value of hs_member_financial_loans_apply.PASSPORT_NUMBER
     *
     * @mbg.generated
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.PASSPORT_NUMBER
     *
     * @param passportNumber the value for hs_member_financial_loans_apply.PASSPORT_NUMBER
     *
     * @mbg.generated
     */
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber == null ? null : passportNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.TELEPHONE
     *
     * @return the value of hs_member_financial_loans_apply.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.TELEPHONE
     *
     * @param telephone the value for hs_member_financial_loans_apply.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.LOAN_AMOUNT
     *
     * @return the value of hs_member_financial_loans_apply.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.LOAN_AMOUNT
     *
     * @param loanAmount the value for hs_member_financial_loans_apply.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.EMAIL
     *
     * @return the value of hs_member_financial_loans_apply.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.EMAIL
     *
     * @param email the value for hs_member_financial_loans_apply.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.FACEBOOK
     *
     * @return the value of hs_member_financial_loans_apply.FACEBOOK
     *
     * @mbg.generated
     */
    public String getFacebook() {
        return facebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.FACEBOOK
     *
     * @param facebook the value for hs_member_financial_loans_apply.FACEBOOK
     *
     * @mbg.generated
     */
    public void setFacebook(String facebook) {
        this.facebook = facebook == null ? null : facebook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.TWITTER
     *
     * @return the value of hs_member_financial_loans_apply.TWITTER
     *
     * @mbg.generated
     */
    public String getTwitter() {
        return twitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.TWITTER
     *
     * @param twitter the value for hs_member_financial_loans_apply.TWITTER
     *
     * @mbg.generated
     */
    public void setTwitter(String twitter) {
        this.twitter = twitter == null ? null : twitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.INSTAGRAM
     *
     * @return the value of hs_member_financial_loans_apply.INSTAGRAM
     *
     * @mbg.generated
     */
    public String getInstagram() {
        return instagram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.INSTAGRAM
     *
     * @param instagram the value for hs_member_financial_loans_apply.INSTAGRAM
     *
     * @mbg.generated
     */
    public void setInstagram(String instagram) {
        this.instagram = instagram == null ? null : instagram.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.PINTEREST
     *
     * @return the value of hs_member_financial_loans_apply.PINTEREST
     *
     * @mbg.generated
     */
    public String getPinterest() {
        return pinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.PINTEREST
     *
     * @param pinterest the value for hs_member_financial_loans_apply.PINTEREST
     *
     * @mbg.generated
     */
    public void setPinterest(String pinterest) {
        this.pinterest = pinterest == null ? null : pinterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.IS_CHECK
     *
     * @return the value of hs_member_financial_loans_apply.IS_CHECK
     *
     * @mbg.generated
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.IS_CHECK
     *
     * @param isCheck the value for hs_member_financial_loans_apply.IS_CHECK
     *
     * @mbg.generated
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.IS_PROCESSOR
     *
     * @return the value of hs_member_financial_loans_apply.IS_PROCESSOR
     *
     * @mbg.generated
     */
    public Integer getIsProcessor() {
        return isProcessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.IS_PROCESSOR
     *
     * @param isProcessor the value for hs_member_financial_loans_apply.IS_PROCESSOR
     *
     * @mbg.generated
     */
    public void setIsProcessor(Integer isProcessor) {
        this.isProcessor = isProcessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.IS_DEL
     *
     * @return the value of hs_member_financial_loans_apply.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.IS_DEL
     *
     * @param isDel the value for hs_member_financial_loans_apply.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.REMARK
     *
     * @return the value of hs_member_financial_loans_apply.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.REMARK
     *
     * @param remark the value for hs_member_financial_loans_apply.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.CREATE_BY
     *
     * @return the value of hs_member_financial_loans_apply.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.CREATE_BY
     *
     * @param createBy the value for hs_member_financial_loans_apply.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.CREATE_TIME
     *
     * @return the value of hs_member_financial_loans_apply.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.CREATE_TIME
     *
     * @param createTime the value for hs_member_financial_loans_apply.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.UPDATE_BY
     *
     * @return the value of hs_member_financial_loans_apply.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.UPDATE_BY
     *
     * @param updateBy the value for hs_member_financial_loans_apply.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.UPDATE_TIME
     *
     * @return the value of hs_member_financial_loans_apply.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.UPDATE_TIME
     *
     * @param updateTime the value for hs_member_financial_loans_apply.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.STANDBY1
     *
     * @return the value of hs_member_financial_loans_apply.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.STANDBY1
     *
     * @param standby1 the value for hs_member_financial_loans_apply.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.STANDBY2
     *
     * @return the value of hs_member_financial_loans_apply.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.STANDBY2
     *
     * @param standby2 the value for hs_member_financial_loans_apply.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.STANDBY3
     *
     * @return the value of hs_member_financial_loans_apply.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.STANDBY3
     *
     * @param standby3 the value for hs_member_financial_loans_apply.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.STANDBY4
     *
     * @return the value of hs_member_financial_loans_apply.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.STANDBY4
     *
     * @param standby4 the value for hs_member_financial_loans_apply.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_member_financial_loans_apply.STANDBY5
     *
     * @return the value of hs_member_financial_loans_apply.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_member_financial_loans_apply.STANDBY5
     *
     * @param standby5 the value for hs_member_financial_loans_apply.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}