package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_sys_role_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsSysRolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   权限id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.PERMISSION_ID
     *
     * @mbg.generated
     */
    private Integer permissionId;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.ROLE_ID
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * Database Column Remarks:
     *   是否禁用,0：启用，1禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.IS_FORBIDDEN
     *
     * @mbg.generated
     */
    private Integer isForbidden;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_role_permission.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.ID
     *
     * @return the value of hs_sys_role_permission.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.ID
     *
     * @param id the value for hs_sys_role_permission.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.PERMISSION_ID
     *
     * @return the value of hs_sys_role_permission.PERMISSION_ID
     *
     * @mbg.generated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.PERMISSION_ID
     *
     * @param permissionId the value for hs_sys_role_permission.PERMISSION_ID
     *
     * @mbg.generated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.ROLE_ID
     *
     * @return the value of hs_sys_role_permission.ROLE_ID
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.ROLE_ID
     *
     * @param roleId the value for hs_sys_role_permission.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.IS_FORBIDDEN
     *
     * @return the value of hs_sys_role_permission.IS_FORBIDDEN
     *
     * @mbg.generated
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.IS_FORBIDDEN
     *
     * @param isForbidden the value for hs_sys_role_permission.IS_FORBIDDEN
     *
     * @mbg.generated
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.CREATE_BY
     *
     * @return the value of hs_sys_role_permission.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.CREATE_BY
     *
     * @param createBy the value for hs_sys_role_permission.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.CREATE_TIME
     *
     * @return the value of hs_sys_role_permission.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.CREATE_TIME
     *
     * @param createTime the value for hs_sys_role_permission.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.UPDATE_BY
     *
     * @return the value of hs_sys_role_permission.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.UPDATE_BY
     *
     * @param updateBy the value for hs_sys_role_permission.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_role_permission.UPDATE_TIME
     *
     * @return the value of hs_sys_role_permission.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_role_permission.UPDATE_TIME
     *
     * @param updateTime the value for hs_sys_role_permission.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}