package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_sys_dictcode_group
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsSysDictcodeGroup implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   字典编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.GROUP_CODE
     *
     * @mbg.generated
     */
    private String groupCode;

    /**
     * Database Column Remarks:
     *   组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.GROUP_NAME
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     * Database Column Remarks:
     *   英文组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.GROUP_NAME_EN
     *
     * @mbg.generated
     */
    private String groupNameEn;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   是否删除0:不删除，1：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_dictcode_group.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.ID
     *
     * @return the value of hs_sys_dictcode_group.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.ID
     *
     * @param id the value for hs_sys_dictcode_group.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.GROUP_CODE
     *
     * @return the value of hs_sys_dictcode_group.GROUP_CODE
     *
     * @mbg.generated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.GROUP_CODE
     *
     * @param groupCode the value for hs_sys_dictcode_group.GROUP_CODE
     *
     * @mbg.generated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.GROUP_NAME
     *
     * @return the value of hs_sys_dictcode_group.GROUP_NAME
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.GROUP_NAME
     *
     * @param groupName the value for hs_sys_dictcode_group.GROUP_NAME
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.GROUP_NAME_EN
     *
     * @return the value of hs_sys_dictcode_group.GROUP_NAME_EN
     *
     * @mbg.generated
     */
    public String getGroupNameEn() {
        return groupNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.GROUP_NAME_EN
     *
     * @param groupNameEn the value for hs_sys_dictcode_group.GROUP_NAME_EN
     *
     * @mbg.generated
     */
    public void setGroupNameEn(String groupNameEn) {
        this.groupNameEn = groupNameEn == null ? null : groupNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.CREATE_BY
     *
     * @return the value of hs_sys_dictcode_group.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.CREATE_BY
     *
     * @param createBy the value for hs_sys_dictcode_group.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.CREATE_TIME
     *
     * @return the value of hs_sys_dictcode_group.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.CREATE_TIME
     *
     * @param createTime the value for hs_sys_dictcode_group.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.UPDATE_BY
     *
     * @return the value of hs_sys_dictcode_group.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.UPDATE_BY
     *
     * @param updateBy the value for hs_sys_dictcode_group.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.UPDATE_TIME
     *
     * @return the value of hs_sys_dictcode_group.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.UPDATE_TIME
     *
     * @param updateTime the value for hs_sys_dictcode_group.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.REMARK
     *
     * @return the value of hs_sys_dictcode_group.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.REMARK
     *
     * @param remark the value for hs_sys_dictcode_group.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.IS_DEL
     *
     * @return the value of hs_sys_dictcode_group.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.IS_DEL
     *
     * @param isDel the value for hs_sys_dictcode_group.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.STANDBY1
     *
     * @return the value of hs_sys_dictcode_group.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.STANDBY1
     *
     * @param standby1 the value for hs_sys_dictcode_group.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.STANDBY2
     *
     * @return the value of hs_sys_dictcode_group.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.STANDBY2
     *
     * @param standby2 the value for hs_sys_dictcode_group.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.STANDBY3
     *
     * @return the value of hs_sys_dictcode_group.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.STANDBY3
     *
     * @param standby3 the value for hs_sys_dictcode_group.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.STANDBY4
     *
     * @return the value of hs_sys_dictcode_group.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.STANDBY4
     *
     * @param standby4 the value for hs_sys_dictcode_group.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_dictcode_group.STANDBY5
     *
     * @return the value of hs_sys_dictcode_group.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_dictcode_group.STANDBY5
     *
     * @param standby5 the value for hs_sys_dictcode_group.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}