package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_sys_platform_setting
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsSysPlatformSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   客服任务结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.CALL_CENTER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String callCenterAssistantRatio;

    /**
     * Database Column Remarks:
     *   外获任务结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.SELLER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String sellerAssistantRatio;

    /**
     * Database Column Remarks:
     *   区域长实勘任务结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.REGION_LEADER_RATIO
     *
     * @mbg.generated
     */
    private String regionLeaderRatio;

    /**
     * Database Column Remarks:
     *   区域长送钥匙任务结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.REGION_LEADER_TAKE_KEY_RATIO
     *
     * @mbg.generated
     */
    private String regionLeaderTakeKeyRatio;

    /**
     * Database Column Remarks:
     *   外看结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.BUYER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String buyerAssistantRatio;

    /**
     * Database Column Remarks:
     *   内勤结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.INTERNAL_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String internalAssistantRatio;

    /**
     * Database Column Remarks:
     *   公司结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.COMPANY_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String companyAssistantRatio;

    /**
     * Database Column Remarks:
     *   其它结佣比例按%分比 格式：0.35-0.45 出租-出售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.ELSE_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    private String elseAssistantRatio;

    /**
     * Database Column Remarks:
     *   出租最低服务费（单位AED）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.RENT_MIN
     *
     * @mbg.generated
     */
    private Double rentMin;

    /**
     * Database Column Remarks:
     *   出售最低服务费（单位AED）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.SELL_MIN
     *
     * @mbg.generated
     */
    private Double sellMin;

    /**
     * Database Column Remarks:
     *   出租服务费比例（百分比）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.RENT_PROPORTION
     *
     * @mbg.generated
     */
    private Double rentProportion;

    /**
     * Database Column Remarks:
     *   出售服务费比例（百分比）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.SELL_PROPORTION
     *
     * @mbg.generated
     */
    private Double sellProportion;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除0:不删除，1：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.STANDBY1
     *
     * @mbg.generated
     */
    private String standby1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.STANDBY2
     *
     * @mbg.generated
     */
    private String standby2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.STANDBY3
     *
     * @mbg.generated
     */
    private String standby3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.STANDBY4
     *
     * @mbg.generated
     */
    private String standby4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_platform_setting.STANDBY5
     *
     * @mbg.generated
     */
    private String standby5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.ID
     *
     * @return the value of hs_sys_platform_setting.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.ID
     *
     * @param id the value for hs_sys_platform_setting.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.CALL_CENTER_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.CALL_CENTER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getCallCenterAssistantRatio() {
        return callCenterAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.CALL_CENTER_ASSISTANT_RATIO
     *
     * @param callCenterAssistantRatio the value for hs_sys_platform_setting.CALL_CENTER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setCallCenterAssistantRatio(String callCenterAssistantRatio) {
        this.callCenterAssistantRatio = callCenterAssistantRatio == null ? null : callCenterAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.SELLER_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.SELLER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getSellerAssistantRatio() {
        return sellerAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.SELLER_ASSISTANT_RATIO
     *
     * @param sellerAssistantRatio the value for hs_sys_platform_setting.SELLER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setSellerAssistantRatio(String sellerAssistantRatio) {
        this.sellerAssistantRatio = sellerAssistantRatio == null ? null : sellerAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.REGION_LEADER_RATIO
     *
     * @return the value of hs_sys_platform_setting.REGION_LEADER_RATIO
     *
     * @mbg.generated
     */
    public String getRegionLeaderRatio() {
        return regionLeaderRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.REGION_LEADER_RATIO
     *
     * @param regionLeaderRatio the value for hs_sys_platform_setting.REGION_LEADER_RATIO
     *
     * @mbg.generated
     */
    public void setRegionLeaderRatio(String regionLeaderRatio) {
        this.regionLeaderRatio = regionLeaderRatio == null ? null : regionLeaderRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.REGION_LEADER_TAKE_KEY_RATIO
     *
     * @return the value of hs_sys_platform_setting.REGION_LEADER_TAKE_KEY_RATIO
     *
     * @mbg.generated
     */
    public String getRegionLeaderTakeKeyRatio() {
        return regionLeaderTakeKeyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.REGION_LEADER_TAKE_KEY_RATIO
     *
     * @param regionLeaderTakeKeyRatio the value for hs_sys_platform_setting.REGION_LEADER_TAKE_KEY_RATIO
     *
     * @mbg.generated
     */
    public void setRegionLeaderTakeKeyRatio(String regionLeaderTakeKeyRatio) {
        this.regionLeaderTakeKeyRatio = regionLeaderTakeKeyRatio == null ? null : regionLeaderTakeKeyRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.BUYER_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.BUYER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getBuyerAssistantRatio() {
        return buyerAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.BUYER_ASSISTANT_RATIO
     *
     * @param buyerAssistantRatio the value for hs_sys_platform_setting.BUYER_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setBuyerAssistantRatio(String buyerAssistantRatio) {
        this.buyerAssistantRatio = buyerAssistantRatio == null ? null : buyerAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.INTERNAL_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.INTERNAL_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getInternalAssistantRatio() {
        return internalAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.INTERNAL_ASSISTANT_RATIO
     *
     * @param internalAssistantRatio the value for hs_sys_platform_setting.INTERNAL_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setInternalAssistantRatio(String internalAssistantRatio) {
        this.internalAssistantRatio = internalAssistantRatio == null ? null : internalAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.COMPANY_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.COMPANY_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getCompanyAssistantRatio() {
        return companyAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.COMPANY_ASSISTANT_RATIO
     *
     * @param companyAssistantRatio the value for hs_sys_platform_setting.COMPANY_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setCompanyAssistantRatio(String companyAssistantRatio) {
        this.companyAssistantRatio = companyAssistantRatio == null ? null : companyAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.ELSE_ASSISTANT_RATIO
     *
     * @return the value of hs_sys_platform_setting.ELSE_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public String getElseAssistantRatio() {
        return elseAssistantRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.ELSE_ASSISTANT_RATIO
     *
     * @param elseAssistantRatio the value for hs_sys_platform_setting.ELSE_ASSISTANT_RATIO
     *
     * @mbg.generated
     */
    public void setElseAssistantRatio(String elseAssistantRatio) {
        this.elseAssistantRatio = elseAssistantRatio == null ? null : elseAssistantRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.RENT_MIN
     *
     * @return the value of hs_sys_platform_setting.RENT_MIN
     *
     * @mbg.generated
     */
    public Double getRentMin() {
        return rentMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.RENT_MIN
     *
     * @param rentMin the value for hs_sys_platform_setting.RENT_MIN
     *
     * @mbg.generated
     */
    public void setRentMin(Double rentMin) {
        this.rentMin = rentMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.SELL_MIN
     *
     * @return the value of hs_sys_platform_setting.SELL_MIN
     *
     * @mbg.generated
     */
    public Double getSellMin() {
        return sellMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.SELL_MIN
     *
     * @param sellMin the value for hs_sys_platform_setting.SELL_MIN
     *
     * @mbg.generated
     */
    public void setSellMin(Double sellMin) {
        this.sellMin = sellMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.RENT_PROPORTION
     *
     * @return the value of hs_sys_platform_setting.RENT_PROPORTION
     *
     * @mbg.generated
     */
    public Double getRentProportion() {
        return rentProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.RENT_PROPORTION
     *
     * @param rentProportion the value for hs_sys_platform_setting.RENT_PROPORTION
     *
     * @mbg.generated
     */
    public void setRentProportion(Double rentProportion) {
        this.rentProportion = rentProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.SELL_PROPORTION
     *
     * @return the value of hs_sys_platform_setting.SELL_PROPORTION
     *
     * @mbg.generated
     */
    public Double getSellProportion() {
        return sellProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.SELL_PROPORTION
     *
     * @param sellProportion the value for hs_sys_platform_setting.SELL_PROPORTION
     *
     * @mbg.generated
     */
    public void setSellProportion(Double sellProportion) {
        this.sellProportion = sellProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.CREATE_BY
     *
     * @return the value of hs_sys_platform_setting.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.CREATE_BY
     *
     * @param createBy the value for hs_sys_platform_setting.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.CREATE_TIME
     *
     * @return the value of hs_sys_platform_setting.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.CREATE_TIME
     *
     * @param createTime the value for hs_sys_platform_setting.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.UPDATE_BY
     *
     * @return the value of hs_sys_platform_setting.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.UPDATE_BY
     *
     * @param updateBy the value for hs_sys_platform_setting.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.UPDATE_TIME
     *
     * @return the value of hs_sys_platform_setting.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.UPDATE_TIME
     *
     * @param updateTime the value for hs_sys_platform_setting.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.IS_DEL
     *
     * @return the value of hs_sys_platform_setting.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.IS_DEL
     *
     * @param isDel the value for hs_sys_platform_setting.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.STANDBY1
     *
     * @return the value of hs_sys_platform_setting.STANDBY1
     *
     * @mbg.generated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.STANDBY1
     *
     * @param standby1 the value for hs_sys_platform_setting.STANDBY1
     *
     * @mbg.generated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.STANDBY2
     *
     * @return the value of hs_sys_platform_setting.STANDBY2
     *
     * @mbg.generated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.STANDBY2
     *
     * @param standby2 the value for hs_sys_platform_setting.STANDBY2
     *
     * @mbg.generated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.STANDBY3
     *
     * @return the value of hs_sys_platform_setting.STANDBY3
     *
     * @mbg.generated
     */
    public String getStandby3() {
        return standby3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.STANDBY3
     *
     * @param standby3 the value for hs_sys_platform_setting.STANDBY3
     *
     * @mbg.generated
     */
    public void setStandby3(String standby3) {
        this.standby3 = standby3 == null ? null : standby3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.STANDBY4
     *
     * @return the value of hs_sys_platform_setting.STANDBY4
     *
     * @mbg.generated
     */
    public String getStandby4() {
        return standby4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.STANDBY4
     *
     * @param standby4 the value for hs_sys_platform_setting.STANDBY4
     *
     * @mbg.generated
     */
    public void setStandby4(String standby4) {
        this.standby4 = standby4 == null ? null : standby4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_platform_setting.STANDBY5
     *
     * @return the value of hs_sys_platform_setting.STANDBY5
     *
     * @mbg.generated
     */
    public String getStandby5() {
        return standby5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_platform_setting.STANDBY5
     *
     * @param standby5 the value for hs_sys_platform_setting.STANDBY5
     *
     * @mbg.generated
     */
    public void setStandby5(String standby5) {
        this.standby5 = standby5 == null ? null : standby5.trim();
    }
}