package www.ucforward.com.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_house_credentials_data
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsHouseCredentialsData implements Serializable{
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   房源申请ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.APPLY_ID
     *
     * @mbg.generated
     */
    private Integer applyId;

    /**
     * Database Column Remarks:
     *   房源id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_ID
     *
     * @mbg.generated
     */
    private Integer houseId;

    /**
     * Database Column Remarks:
     *   语言版本(0:中文,1:英文)默认为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    private Integer languageVersion;

    /**
     * Database Column Remarks:
     *   申请人类型：0业主 1 poa 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.APPLICANT_TYPE
     *
     * @mbg.generated
     */
    private Integer applicantType;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG1
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg1;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG2
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg2;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG3
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg3;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG4
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg4;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG5
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg5;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG6
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg6;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG7
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg7;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG8
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg8;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG9
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg9;

    /**
     * Database Column Remarks:
     *   POA复印件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_COPIES_IMG10
     *
     * @mbg.generated
     */
    private String mandataryCopiesImg10;

    /**
     * Database Column Remarks:
     *   被委托人护照照片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    private String mandataryPassportImg1;

    /**
     * Database Column Remarks:
     *   被委托人护照照片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    private String mandataryPassportImg2;

    /**
     * Database Column Remarks:
     *   被委托人护照照片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    private String mandataryPassportImg3;

    /**
     * Database Column Remarks:
     *   被委托人签证照片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_VISA_IMG1
     *
     * @mbg.generated
     */
    private String mandataryVisaImg1;

    /**
     * Database Column Remarks:
     *   被委托人签证照片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_VISA_IMG2
     *
     * @mbg.generated
     */
    private String mandataryVisaImg2;

    /**
     * Database Column Remarks:
     *   被委托人签证照片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_VISA_IMG3
     *
     * @mbg.generated
     */
    private String mandataryVisaImg3;

    /**
     * Database Column Remarks:
     *   被委托人ID卡照片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG1
     *
     * @mbg.generated
     */
    private String mandataryIdcardImg1;

    /**
     * Database Column Remarks:
     *   被委托人ID卡照片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG2
     *
     * @mbg.generated
     */
    private String mandataryIdcardImg2;

    /**
     * Database Column Remarks:
     *   被委托人ID卡照片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG3
     *
     * @mbg.generated
     */
    private String mandataryIdcardImg3;

    /**
     * Database Column Remarks:
     *   被委托人ID卡照片4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG4
     *
     * @mbg.generated
     */
    private String mandataryIdcardImg4;

    /**
     * Database Column Remarks:
     *   委托书1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.LETTER_AUTHORIZATION
     *
     * @mbg.generated
     */
    private String letterAuthorization;

    /**
     * Database Column Remarks:
     *   委托书2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.LETTER_AUTHORIZATION2
     *
     * @mbg.generated
     */
    private String letterAuthorization2;

    /**
     * Database Column Remarks:
     *   房屋租赁委托人签字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG1
     *
     * @mbg.generated
     */
    private String rentAuthorizationSignImg1;

    /**
     * Database Column Remarks:
     *   房屋租赁委托人签字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG2
     *
     * @mbg.generated
     */
    private String rentAuthorizationSignImg2;

    /**
     * Database Column Remarks:
     *   房屋租赁委托人签字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG3
     *
     * @mbg.generated
     */
    private String rentAuthorizationSignImg3;

    /**
     * Database Column Remarks:
     *   formA确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.FORMA_CONFIRM_IMG1
     *
     * @mbg.generated
     */
    private String formaConfirmImg1;

    /**
     * Database Column Remarks:
     *   formA确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.FORMA_CONFIRM_IMG2
     *
     * @mbg.generated
     */
    private String formaConfirmImg2;

    /**
     * Database Column Remarks:
     *   formA确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.FORMA_CONFIRM_IMG3
     *
     * @mbg.generated
     */
    private String formaConfirmImg3;

    /**
     * Database Column Remarks:
     *   房产证照片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.POC_IMG1
     *
     * @mbg.generated
     */
    private String pocImg1;

    /**
     * Database Column Remarks:
     *   房产证照片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.POC_IMG2
     *
     * @mbg.generated
     */
    private String pocImg2;

    /**
     * Database Column Remarks:
     *   房产证照片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.POC_IMG3
     *
     * @mbg.generated
     */
    private String pocImg3;

    /**
     * Database Column Remarks:
     *   房屋产权人护照照片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.REO_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    private String reoPassportImg1;

    /**
     * Database Column Remarks:
     *   房屋产权人护照照片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.REO_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    private String reoPassportImg2;

    /**
     * Database Column Remarks:
     *   房屋产权人护照照片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.REO_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    private String reoPassportImg3;

    /**
     * Database Column Remarks:
     *   房屋租赁合同图片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG1
     *
     * @mbg.generated
     */
    private String houseRentContractImg1;

    /**
     * Database Column Remarks:
     *   房屋租赁合同图片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG2
     *
     * @mbg.generated
     */
    private String houseRentContractImg2;

    /**
     * Database Column Remarks:
     *   房屋租赁合同图片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG3
     *
     * @mbg.generated
     */
    private String houseRentContractImg3;

    /**
     * Database Column Remarks:
     *   房屋租赁合同图片4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG4
     *
     * @mbg.generated
     */
    private String houseRentContractImg4;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG1
     *
     * @mbg.generated
     */
    private String houseHoldImg1;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG2
     *
     * @mbg.generated
     */
    private String houseHoldImg2;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG3
     *
     * @mbg.generated
     */
    private String houseHoldImg3;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG4
     *
     * @mbg.generated
     */
    private String houseHoldImg4;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG5
     *
     * @mbg.generated
     */
    private String houseHoldImg5;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG6
     *
     * @mbg.generated
     */
    private String houseHoldImg6;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG7
     *
     * @mbg.generated
     */
    private String houseHoldImg7;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG8
     *
     * @mbg.generated
     */
    private String houseHoldImg8;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG9
     *
     * @mbg.generated
     */
    private String houseHoldImg9;

    /**
     * Database Column Remarks:
     *   房屋户型图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_house_credentials_data.HOUSE_HOLD_IMG10
     *
     * @mbg.generated
     */
    private String houseHoldImg10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.ID
     *
     * @return the value of hs_house_credentials_data.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.ID
     *
     * @param id the value for hs_house_credentials_data.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.APPLY_ID
     *
     * @return the value of hs_house_credentials_data.APPLY_ID
     *
     * @mbg.generated
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.APPLY_ID
     *
     * @param applyId the value for hs_house_credentials_data.APPLY_ID
     *
     * @mbg.generated
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_ID
     *
     * @return the value of hs_house_credentials_data.HOUSE_ID
     *
     * @mbg.generated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_ID
     *
     * @param houseId the value for hs_house_credentials_data.HOUSE_ID
     *
     * @mbg.generated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.LANGUAGE_VERSION
     *
     * @return the value of hs_house_credentials_data.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public Integer getLanguageVersion() {
        return languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.LANGUAGE_VERSION
     *
     * @param languageVersion the value for hs_house_credentials_data.LANGUAGE_VERSION
     *
     * @mbg.generated
     */
    public void setLanguageVersion(Integer languageVersion) {
        this.languageVersion = languageVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.APPLICANT_TYPE
     *
     * @return the value of hs_house_credentials_data.APPLICANT_TYPE
     *
     * @mbg.generated
     */
    public Integer getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.APPLICANT_TYPE
     *
     * @param applicantType the value for hs_house_credentials_data.APPLICANT_TYPE
     *
     * @mbg.generated
     */
    public void setApplicantType(Integer applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG1
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG1
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg1() {
        return mandataryCopiesImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG1
     *
     * @param mandataryCopiesImg1 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG1
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg1(String mandataryCopiesImg1) {
        this.mandataryCopiesImg1 = mandataryCopiesImg1 == null ? null : mandataryCopiesImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG2
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG2
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg2() {
        return mandataryCopiesImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG2
     *
     * @param mandataryCopiesImg2 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG2
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg2(String mandataryCopiesImg2) {
        this.mandataryCopiesImg2 = mandataryCopiesImg2 == null ? null : mandataryCopiesImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG3
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG3
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg3() {
        return mandataryCopiesImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG3
     *
     * @param mandataryCopiesImg3 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG3
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg3(String mandataryCopiesImg3) {
        this.mandataryCopiesImg3 = mandataryCopiesImg3 == null ? null : mandataryCopiesImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG4
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG4
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg4() {
        return mandataryCopiesImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG4
     *
     * @param mandataryCopiesImg4 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG4
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg4(String mandataryCopiesImg4) {
        this.mandataryCopiesImg4 = mandataryCopiesImg4 == null ? null : mandataryCopiesImg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG5
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG5
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg5() {
        return mandataryCopiesImg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG5
     *
     * @param mandataryCopiesImg5 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG5
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg5(String mandataryCopiesImg5) {
        this.mandataryCopiesImg5 = mandataryCopiesImg5 == null ? null : mandataryCopiesImg5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG6
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG6
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg6() {
        return mandataryCopiesImg6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG6
     *
     * @param mandataryCopiesImg6 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG6
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg6(String mandataryCopiesImg6) {
        this.mandataryCopiesImg6 = mandataryCopiesImg6 == null ? null : mandataryCopiesImg6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG7
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG7
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg7() {
        return mandataryCopiesImg7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG7
     *
     * @param mandataryCopiesImg7 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG7
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg7(String mandataryCopiesImg7) {
        this.mandataryCopiesImg7 = mandataryCopiesImg7 == null ? null : mandataryCopiesImg7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG8
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG8
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg8() {
        return mandataryCopiesImg8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG8
     *
     * @param mandataryCopiesImg8 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG8
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg8(String mandataryCopiesImg8) {
        this.mandataryCopiesImg8 = mandataryCopiesImg8 == null ? null : mandataryCopiesImg8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG9
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG9
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg9() {
        return mandataryCopiesImg9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG9
     *
     * @param mandataryCopiesImg9 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG9
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg9(String mandataryCopiesImg9) {
        this.mandataryCopiesImg9 = mandataryCopiesImg9 == null ? null : mandataryCopiesImg9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG10
     *
     * @return the value of hs_house_credentials_data.MANDATARY_COPIES_IMG10
     *
     * @mbg.generated
     */
    public String getMandataryCopiesImg10() {
        return mandataryCopiesImg10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_COPIES_IMG10
     *
     * @param mandataryCopiesImg10 the value for hs_house_credentials_data.MANDATARY_COPIES_IMG10
     *
     * @mbg.generated
     */
    public void setMandataryCopiesImg10(String mandataryCopiesImg10) {
        this.mandataryCopiesImg10 = mandataryCopiesImg10 == null ? null : mandataryCopiesImg10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG1
     *
     * @return the value of hs_house_credentials_data.MANDATARY_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    public String getMandataryPassportImg1() {
        return mandataryPassportImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG1
     *
     * @param mandataryPassportImg1 the value for hs_house_credentials_data.MANDATARY_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    public void setMandataryPassportImg1(String mandataryPassportImg1) {
        this.mandataryPassportImg1 = mandataryPassportImg1 == null ? null : mandataryPassportImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG2
     *
     * @return the value of hs_house_credentials_data.MANDATARY_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    public String getMandataryPassportImg2() {
        return mandataryPassportImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG2
     *
     * @param mandataryPassportImg2 the value for hs_house_credentials_data.MANDATARY_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    public void setMandataryPassportImg2(String mandataryPassportImg2) {
        this.mandataryPassportImg2 = mandataryPassportImg2 == null ? null : mandataryPassportImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG3
     *
     * @return the value of hs_house_credentials_data.MANDATARY_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    public String getMandataryPassportImg3() {
        return mandataryPassportImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_PASSPORT_IMG3
     *
     * @param mandataryPassportImg3 the value for hs_house_credentials_data.MANDATARY_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    public void setMandataryPassportImg3(String mandataryPassportImg3) {
        this.mandataryPassportImg3 = mandataryPassportImg3 == null ? null : mandataryPassportImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG1
     *
     * @return the value of hs_house_credentials_data.MANDATARY_VISA_IMG1
     *
     * @mbg.generated
     */
    public String getMandataryVisaImg1() {
        return mandataryVisaImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG1
     *
     * @param mandataryVisaImg1 the value for hs_house_credentials_data.MANDATARY_VISA_IMG1
     *
     * @mbg.generated
     */
    public void setMandataryVisaImg1(String mandataryVisaImg1) {
        this.mandataryVisaImg1 = mandataryVisaImg1 == null ? null : mandataryVisaImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG2
     *
     * @return the value of hs_house_credentials_data.MANDATARY_VISA_IMG2
     *
     * @mbg.generated
     */
    public String getMandataryVisaImg2() {
        return mandataryVisaImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG2
     *
     * @param mandataryVisaImg2 the value for hs_house_credentials_data.MANDATARY_VISA_IMG2
     *
     * @mbg.generated
     */
    public void setMandataryVisaImg2(String mandataryVisaImg2) {
        this.mandataryVisaImg2 = mandataryVisaImg2 == null ? null : mandataryVisaImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG3
     *
     * @return the value of hs_house_credentials_data.MANDATARY_VISA_IMG3
     *
     * @mbg.generated
     */
    public String getMandataryVisaImg3() {
        return mandataryVisaImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_VISA_IMG3
     *
     * @param mandataryVisaImg3 the value for hs_house_credentials_data.MANDATARY_VISA_IMG3
     *
     * @mbg.generated
     */
    public void setMandataryVisaImg3(String mandataryVisaImg3) {
        this.mandataryVisaImg3 = mandataryVisaImg3 == null ? null : mandataryVisaImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG1
     *
     * @return the value of hs_house_credentials_data.MANDATARY_IDCARD_IMG1
     *
     * @mbg.generated
     */
    public String getMandataryIdcardImg1() {
        return mandataryIdcardImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG1
     *
     * @param mandataryIdcardImg1 the value for hs_house_credentials_data.MANDATARY_IDCARD_IMG1
     *
     * @mbg.generated
     */
    public void setMandataryIdcardImg1(String mandataryIdcardImg1) {
        this.mandataryIdcardImg1 = mandataryIdcardImg1 == null ? null : mandataryIdcardImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG2
     *
     * @return the value of hs_house_credentials_data.MANDATARY_IDCARD_IMG2
     *
     * @mbg.generated
     */
    public String getMandataryIdcardImg2() {
        return mandataryIdcardImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG2
     *
     * @param mandataryIdcardImg2 the value for hs_house_credentials_data.MANDATARY_IDCARD_IMG2
     *
     * @mbg.generated
     */
    public void setMandataryIdcardImg2(String mandataryIdcardImg2) {
        this.mandataryIdcardImg2 = mandataryIdcardImg2 == null ? null : mandataryIdcardImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG3
     *
     * @return the value of hs_house_credentials_data.MANDATARY_IDCARD_IMG3
     *
     * @mbg.generated
     */
    public String getMandataryIdcardImg3() {
        return mandataryIdcardImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG3
     *
     * @param mandataryIdcardImg3 the value for hs_house_credentials_data.MANDATARY_IDCARD_IMG3
     *
     * @mbg.generated
     */
    public void setMandataryIdcardImg3(String mandataryIdcardImg3) {
        this.mandataryIdcardImg3 = mandataryIdcardImg3 == null ? null : mandataryIdcardImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG4
     *
     * @return the value of hs_house_credentials_data.MANDATARY_IDCARD_IMG4
     *
     * @mbg.generated
     */
    public String getMandataryIdcardImg4() {
        return mandataryIdcardImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.MANDATARY_IDCARD_IMG4
     *
     * @param mandataryIdcardImg4 the value for hs_house_credentials_data.MANDATARY_IDCARD_IMG4
     *
     * @mbg.generated
     */
    public void setMandataryIdcardImg4(String mandataryIdcardImg4) {
        this.mandataryIdcardImg4 = mandataryIdcardImg4 == null ? null : mandataryIdcardImg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.LETTER_AUTHORIZATION
     *
     * @return the value of hs_house_credentials_data.LETTER_AUTHORIZATION
     *
     * @mbg.generated
     */
    public String getLetterAuthorization() {
        return letterAuthorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.LETTER_AUTHORIZATION
     *
     * @param letterAuthorization the value for hs_house_credentials_data.LETTER_AUTHORIZATION
     *
     * @mbg.generated
     */
    public void setLetterAuthorization(String letterAuthorization) {
        this.letterAuthorization = letterAuthorization == null ? null : letterAuthorization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.LETTER_AUTHORIZATION2
     *
     * @return the value of hs_house_credentials_data.LETTER_AUTHORIZATION2
     *
     * @mbg.generated
     */
    public String getLetterAuthorization2() {
        return letterAuthorization2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.LETTER_AUTHORIZATION2
     *
     * @param letterAuthorization2 the value for hs_house_credentials_data.LETTER_AUTHORIZATION2
     *
     * @mbg.generated
     */
    public void setLetterAuthorization2(String letterAuthorization2) {
        this.letterAuthorization2 = letterAuthorization2 == null ? null : letterAuthorization2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG1
     *
     * @return the value of hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG1
     *
     * @mbg.generated
     */
    public String getRentAuthorizationSignImg1() {
        return rentAuthorizationSignImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG1
     *
     * @param rentAuthorizationSignImg1 the value for hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG1
     *
     * @mbg.generated
     */
    public void setRentAuthorizationSignImg1(String rentAuthorizationSignImg1) {
        this.rentAuthorizationSignImg1 = rentAuthorizationSignImg1 == null ? null : rentAuthorizationSignImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG2
     *
     * @return the value of hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG2
     *
     * @mbg.generated
     */
    public String getRentAuthorizationSignImg2() {
        return rentAuthorizationSignImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG2
     *
     * @param rentAuthorizationSignImg2 the value for hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG2
     *
     * @mbg.generated
     */
    public void setRentAuthorizationSignImg2(String rentAuthorizationSignImg2) {
        this.rentAuthorizationSignImg2 = rentAuthorizationSignImg2 == null ? null : rentAuthorizationSignImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG3
     *
     * @return the value of hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG3
     *
     * @mbg.generated
     */
    public String getRentAuthorizationSignImg3() {
        return rentAuthorizationSignImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG3
     *
     * @param rentAuthorizationSignImg3 the value for hs_house_credentials_data.RENT_AUTHORIZATION_SIGN_IMG3
     *
     * @mbg.generated
     */
    public void setRentAuthorizationSignImg3(String rentAuthorizationSignImg3) {
        this.rentAuthorizationSignImg3 = rentAuthorizationSignImg3 == null ? null : rentAuthorizationSignImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG1
     *
     * @return the value of hs_house_credentials_data.FORMA_CONFIRM_IMG1
     *
     * @mbg.generated
     */
    public String getFormaConfirmImg1() {
        return formaConfirmImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG1
     *
     * @param formaConfirmImg1 the value for hs_house_credentials_data.FORMA_CONFIRM_IMG1
     *
     * @mbg.generated
     */
    public void setFormaConfirmImg1(String formaConfirmImg1) {
        this.formaConfirmImg1 = formaConfirmImg1 == null ? null : formaConfirmImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG2
     *
     * @return the value of hs_house_credentials_data.FORMA_CONFIRM_IMG2
     *
     * @mbg.generated
     */
    public String getFormaConfirmImg2() {
        return formaConfirmImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG2
     *
     * @param formaConfirmImg2 the value for hs_house_credentials_data.FORMA_CONFIRM_IMG2
     *
     * @mbg.generated
     */
    public void setFormaConfirmImg2(String formaConfirmImg2) {
        this.formaConfirmImg2 = formaConfirmImg2 == null ? null : formaConfirmImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG3
     *
     * @return the value of hs_house_credentials_data.FORMA_CONFIRM_IMG3
     *
     * @mbg.generated
     */
    public String getFormaConfirmImg3() {
        return formaConfirmImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.FORMA_CONFIRM_IMG3
     *
     * @param formaConfirmImg3 the value for hs_house_credentials_data.FORMA_CONFIRM_IMG3
     *
     * @mbg.generated
     */
    public void setFormaConfirmImg3(String formaConfirmImg3) {
        this.formaConfirmImg3 = formaConfirmImg3 == null ? null : formaConfirmImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.POC_IMG1
     *
     * @return the value of hs_house_credentials_data.POC_IMG1
     *
     * @mbg.generated
     */
    public String getPocImg1() {
        return pocImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.POC_IMG1
     *
     * @param pocImg1 the value for hs_house_credentials_data.POC_IMG1
     *
     * @mbg.generated
     */
    public void setPocImg1(String pocImg1) {
        this.pocImg1 = pocImg1 == null ? null : pocImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.POC_IMG2
     *
     * @return the value of hs_house_credentials_data.POC_IMG2
     *
     * @mbg.generated
     */
    public String getPocImg2() {
        return pocImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.POC_IMG2
     *
     * @param pocImg2 the value for hs_house_credentials_data.POC_IMG2
     *
     * @mbg.generated
     */
    public void setPocImg2(String pocImg2) {
        this.pocImg2 = pocImg2 == null ? null : pocImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.POC_IMG3
     *
     * @return the value of hs_house_credentials_data.POC_IMG3
     *
     * @mbg.generated
     */
    public String getPocImg3() {
        return pocImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.POC_IMG3
     *
     * @param pocImg3 the value for hs_house_credentials_data.POC_IMG3
     *
     * @mbg.generated
     */
    public void setPocImg3(String pocImg3) {
        this.pocImg3 = pocImg3 == null ? null : pocImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG1
     *
     * @return the value of hs_house_credentials_data.REO_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    public String getReoPassportImg1() {
        return reoPassportImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG1
     *
     * @param reoPassportImg1 the value for hs_house_credentials_data.REO_PASSPORT_IMG1
     *
     * @mbg.generated
     */
    public void setReoPassportImg1(String reoPassportImg1) {
        this.reoPassportImg1 = reoPassportImg1 == null ? null : reoPassportImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG2
     *
     * @return the value of hs_house_credentials_data.REO_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    public String getReoPassportImg2() {
        return reoPassportImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG2
     *
     * @param reoPassportImg2 the value for hs_house_credentials_data.REO_PASSPORT_IMG2
     *
     * @mbg.generated
     */
    public void setReoPassportImg2(String reoPassportImg2) {
        this.reoPassportImg2 = reoPassportImg2 == null ? null : reoPassportImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG3
     *
     * @return the value of hs_house_credentials_data.REO_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    public String getReoPassportImg3() {
        return reoPassportImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.REO_PASSPORT_IMG3
     *
     * @param reoPassportImg3 the value for hs_house_credentials_data.REO_PASSPORT_IMG3
     *
     * @mbg.generated
     */
    public void setReoPassportImg3(String reoPassportImg3) {
        this.reoPassportImg3 = reoPassportImg3 == null ? null : reoPassportImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG1
     *
     * @return the value of hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG1
     *
     * @mbg.generated
     */
    public String getHouseRentContractImg1() {
        return houseRentContractImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG1
     *
     * @param houseRentContractImg1 the value for hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG1
     *
     * @mbg.generated
     */
    public void setHouseRentContractImg1(String houseRentContractImg1) {
        this.houseRentContractImg1 = houseRentContractImg1 == null ? null : houseRentContractImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG2
     *
     * @return the value of hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG2
     *
     * @mbg.generated
     */
    public String getHouseRentContractImg2() {
        return houseRentContractImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG2
     *
     * @param houseRentContractImg2 the value for hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG2
     *
     * @mbg.generated
     */
    public void setHouseRentContractImg2(String houseRentContractImg2) {
        this.houseRentContractImg2 = houseRentContractImg2 == null ? null : houseRentContractImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG3
     *
     * @return the value of hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG3
     *
     * @mbg.generated
     */
    public String getHouseRentContractImg3() {
        return houseRentContractImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG3
     *
     * @param houseRentContractImg3 the value for hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG3
     *
     * @mbg.generated
     */
    public void setHouseRentContractImg3(String houseRentContractImg3) {
        this.houseRentContractImg3 = houseRentContractImg3 == null ? null : houseRentContractImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG4
     *
     * @return the value of hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG4
     *
     * @mbg.generated
     */
    public String getHouseRentContractImg4() {
        return houseRentContractImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG4
     *
     * @param houseRentContractImg4 the value for hs_house_credentials_data.HOUSE_RENT_CONTRACT_IMG4
     *
     * @mbg.generated
     */
    public void setHouseRentContractImg4(String houseRentContractImg4) {
        this.houseRentContractImg4 = houseRentContractImg4 == null ? null : houseRentContractImg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG1
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG1
     *
     * @mbg.generated
     */
    public String getHouseHoldImg1() {
        return houseHoldImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG1
     *
     * @param houseHoldImg1 the value for hs_house_credentials_data.HOUSE_HOLD_IMG1
     *
     * @mbg.generated
     */
    public void setHouseHoldImg1(String houseHoldImg1) {
        this.houseHoldImg1 = houseHoldImg1 == null ? null : houseHoldImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG2
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG2
     *
     * @mbg.generated
     */
    public String getHouseHoldImg2() {
        return houseHoldImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG2
     *
     * @param houseHoldImg2 the value for hs_house_credentials_data.HOUSE_HOLD_IMG2
     *
     * @mbg.generated
     */
    public void setHouseHoldImg2(String houseHoldImg2) {
        this.houseHoldImg2 = houseHoldImg2 == null ? null : houseHoldImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG3
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG3
     *
     * @mbg.generated
     */
    public String getHouseHoldImg3() {
        return houseHoldImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG3
     *
     * @param houseHoldImg3 the value for hs_house_credentials_data.HOUSE_HOLD_IMG3
     *
     * @mbg.generated
     */
    public void setHouseHoldImg3(String houseHoldImg3) {
        this.houseHoldImg3 = houseHoldImg3 == null ? null : houseHoldImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG4
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG4
     *
     * @mbg.generated
     */
    public String getHouseHoldImg4() {
        return houseHoldImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG4
     *
     * @param houseHoldImg4 the value for hs_house_credentials_data.HOUSE_HOLD_IMG4
     *
     * @mbg.generated
     */
    public void setHouseHoldImg4(String houseHoldImg4) {
        this.houseHoldImg4 = houseHoldImg4 == null ? null : houseHoldImg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG5
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG5
     *
     * @mbg.generated
     */
    public String getHouseHoldImg5() {
        return houseHoldImg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG5
     *
     * @param houseHoldImg5 the value for hs_house_credentials_data.HOUSE_HOLD_IMG5
     *
     * @mbg.generated
     */
    public void setHouseHoldImg5(String houseHoldImg5) {
        this.houseHoldImg5 = houseHoldImg5 == null ? null : houseHoldImg5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG6
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG6
     *
     * @mbg.generated
     */
    public String getHouseHoldImg6() {
        return houseHoldImg6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG6
     *
     * @param houseHoldImg6 the value for hs_house_credentials_data.HOUSE_HOLD_IMG6
     *
     * @mbg.generated
     */
    public void setHouseHoldImg6(String houseHoldImg6) {
        this.houseHoldImg6 = houseHoldImg6 == null ? null : houseHoldImg6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG7
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG7
     *
     * @mbg.generated
     */
    public String getHouseHoldImg7() {
        return houseHoldImg7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG7
     *
     * @param houseHoldImg7 the value for hs_house_credentials_data.HOUSE_HOLD_IMG7
     *
     * @mbg.generated
     */
    public void setHouseHoldImg7(String houseHoldImg7) {
        this.houseHoldImg7 = houseHoldImg7 == null ? null : houseHoldImg7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG8
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG8
     *
     * @mbg.generated
     */
    public String getHouseHoldImg8() {
        return houseHoldImg8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG8
     *
     * @param houseHoldImg8 the value for hs_house_credentials_data.HOUSE_HOLD_IMG8
     *
     * @mbg.generated
     */
    public void setHouseHoldImg8(String houseHoldImg8) {
        this.houseHoldImg8 = houseHoldImg8 == null ? null : houseHoldImg8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG9
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG9
     *
     * @mbg.generated
     */
    public String getHouseHoldImg9() {
        return houseHoldImg9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG9
     *
     * @param houseHoldImg9 the value for hs_house_credentials_data.HOUSE_HOLD_IMG9
     *
     * @mbg.generated
     */
    public void setHouseHoldImg9(String houseHoldImg9) {
        this.houseHoldImg9 = houseHoldImg9 == null ? null : houseHoldImg9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG10
     *
     * @return the value of hs_house_credentials_data.HOUSE_HOLD_IMG10
     *
     * @mbg.generated
     */
    public String getHouseHoldImg10() {
        return houseHoldImg10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_house_credentials_data.HOUSE_HOLD_IMG10
     *
     * @param houseHoldImg10 the value for hs_house_credentials_data.HOUSE_HOLD_IMG10
     *
     * @mbg.generated
     */
    public void setHouseHoldImg10(String houseHoldImg10) {
        this.houseHoldImg10 = houseHoldImg10 == null ? null : houseHoldImg10.trim();
    }
}