package www.ucforward.com.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hs_sys_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class HsSysUser implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.USERCODE
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.INVITATION_CODE
     *
     * @mbg.generated
     */
    private Integer invitationCode;

    /**
     * Database Column Remarks:
     *   个人头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.USER_LOGO
     *
     * @mbg.generated
     */
    private String userLogo;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   盐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.SALT
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   账号是否锁( 0未锁定 , 1：锁定)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.LOCKED
     *
     * @mbg.generated
     */
    private Integer locked;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.CITY
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   社区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.COMMUNITY
     *
     * @mbg.generated
     */
    private String community;

    /**
     * Database Column Remarks:
     *   子社区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.SUB_COMMUNITY
     *
     * @mbg.generated
     */
    private String subCommunity;

    /**
     * Database Column Remarks:
     *   积分帐户,默认为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.GOLD
     *
     * @mbg.generated
     */
    private Integer gold;

    /**
     * Database Column Remarks:
     *   是否删除( 0：未删除， 1:删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.IS_DEL
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_sys_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.ID
     *
     * @return the value of hs_sys_user.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.ID
     *
     * @param id the value for hs_sys_user.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.USERCODE
     *
     * @return the value of hs_sys_user.USERCODE
     *
     * @mbg.generated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.USERCODE
     *
     * @param usercode the value for hs_sys_user.USERCODE
     *
     * @mbg.generated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.USERNAME
     *
     * @return the value of hs_sys_user.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.USERNAME
     *
     * @param username the value for hs_sys_user.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.PASSWORD
     *
     * @return the value of hs_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.PASSWORD
     *
     * @param password the value for hs_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.INVITATION_CODE
     *
     * @return the value of hs_sys_user.INVITATION_CODE
     *
     * @mbg.generated
     */
    public Integer getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.INVITATION_CODE
     *
     * @param invitationCode the value for hs_sys_user.INVITATION_CODE
     *
     * @mbg.generated
     */
    public void setInvitationCode(Integer invitationCode) {
        this.invitationCode = invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.USER_LOGO
     *
     * @return the value of hs_sys_user.USER_LOGO
     *
     * @mbg.generated
     */
    public String getUserLogo() {
        return userLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.USER_LOGO
     *
     * @param userLogo the value for hs_sys_user.USER_LOGO
     *
     * @mbg.generated
     */
    public void setUserLogo(String userLogo) {
        this.userLogo = userLogo == null ? null : userLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.MOBILE
     *
     * @return the value of hs_sys_user.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.MOBILE
     *
     * @param mobile the value for hs_sys_user.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.SALT
     *
     * @return the value of hs_sys_user.SALT
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.SALT
     *
     * @param salt the value for hs_sys_user.SALT
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.LOCKED
     *
     * @return the value of hs_sys_user.LOCKED
     *
     * @mbg.generated
     */
    public Integer getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.LOCKED
     *
     * @param locked the value for hs_sys_user.LOCKED
     *
     * @mbg.generated
     */
    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.CITY
     *
     * @return the value of hs_sys_user.CITY
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.CITY
     *
     * @param city the value for hs_sys_user.CITY
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.COMMUNITY
     *
     * @return the value of hs_sys_user.COMMUNITY
     *
     * @mbg.generated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.COMMUNITY
     *
     * @param community the value for hs_sys_user.COMMUNITY
     *
     * @mbg.generated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.SUB_COMMUNITY
     *
     * @return the value of hs_sys_user.SUB_COMMUNITY
     *
     * @mbg.generated
     */
    public String getSubCommunity() {
        return subCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.SUB_COMMUNITY
     *
     * @param subCommunity the value for hs_sys_user.SUB_COMMUNITY
     *
     * @mbg.generated
     */
    public void setSubCommunity(String subCommunity) {
        this.subCommunity = subCommunity == null ? null : subCommunity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.GOLD
     *
     * @return the value of hs_sys_user.GOLD
     *
     * @mbg.generated
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.GOLD
     *
     * @param gold the value for hs_sys_user.GOLD
     *
     * @mbg.generated
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.IS_DEL
     *
     * @return the value of hs_sys_user.IS_DEL
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.IS_DEL
     *
     * @param isDel the value for hs_sys_user.IS_DEL
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.CREATE_BY
     *
     * @return the value of hs_sys_user.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.CREATE_BY
     *
     * @param createBy the value for hs_sys_user.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.CREATE_TIME
     *
     * @return the value of hs_sys_user.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.CREATE_TIME
     *
     * @param createTime the value for hs_sys_user.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.UPDATE_BY
     *
     * @return the value of hs_sys_user.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.UPDATE_BY
     *
     * @param updateBy the value for hs_sys_user.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_sys_user.UPDATE_TIME
     *
     * @return the value of hs_sys_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_sys_user.UPDATE_TIME
     *
     * @param updateTime the value for hs_sys_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}